/* Data Mining 互動考題 — 題庫資料（中英雙語）
 * Bilingual question bank for the Data Mining Interactive Tutorial.
 * 20 章 × 10 題 = 200 題；每章 6 single + 2 multi + 2 tf
 * Format:
 *   { ch:1..20, type:'single'|'multi'|'tf',
 *     stem_zh, stem_en,
 *     options_zh:[..], options_en:[..],   // single/multi only
 *     answer: int | int[] | 0|1,           // tf: 0=False, 1=True
 *     exp_zh, exp_en }
 */
window.QUIZ_CHAPTERS = [
  { id:1,  zh:"CRISP-DM 與資料探勘導論",    en:"Intro & CRISP-DM" },
  { id:2,  zh:"資料準備與前處理",            en:"Data Preparation" },
  { id:3,  zh:"EDA 與視覺化",                en:"EDA & Visualization" },
  { id:4,  zh:"相似度與距離度量",            en:"Similarity & Distance" },
  { id:5,  zh:"分類概論：KNN / Logistic",    en:"Classification Overview" },
  { id:6,  zh:"決策樹與隨機森林",            en:"Decision Trees & Random Forest" },
  { id:7,  zh:"樸素貝氏與 SVM",              en:"Naive Bayes & SVM" },
  { id:8,  zh:"模型評估與調參",              en:"Model Evaluation & Tuning" },
  { id:9,  zh:"K-Means 與階層分群",          en:"K-Means & Hierarchical Clustering" },
  { id:10, zh:"密度型分群 (DBSCAN/HDBSCAN)", en:"Density-Based Clustering" },
  { id:11, zh:"關聯規則 (Apriori/FP-Growth)",en:"Association Rules" },
  { id:12, zh:"序列樣式探勘",                en:"Sequential Pattern Mining" },
  { id:13, zh:"異常偵測",                    en:"Anomaly Detection" },
  { id:14, zh:"文本探勘與 NLP",              en:"Text Mining & NLP" },
  { id:15, zh:"時序資料探勘",                en:"Time Series Mining" },
  { id:16, zh:"圖與網絡探勘",                en:"Graph & Network Mining" },
  { id:17, zh:"EHR 資料探勘",                en:"EHR Mining" },
  { id:18, zh:"組學資料探勘",                en:"Omics Mining" },
  { id:19, zh:"文獻探勘",                    en:"Literature Mining (PubMed)" },
  { id:20, zh:"倫理與可重現性",              en:"Ethics & Reproducibility" }
];

window.QUIZ_DATA = [
/* ========== Ch.1 CRISP-DM 與資料探勘導論 ========== */
{ch:1,type:'single',
 stem_zh:"CRISP-DM 由幾個階段組成？",
 stem_en:"How many phases make up CRISP-DM?",
 options_zh:["4","5","6","7"],
 options_en:["4","5","6","7"],
 answer:2,
 exp_zh:"CRISP-DM 1.0 (1999) 定義 6 個階段：商業理解、資料理解、資料準備、建模、評估、部署。",
 exp_en:"CRISP-DM 1.0 (1999) defines 6 phases: Business Understanding, Data Understanding, Data Preparation, Modeling, Evaluation, Deployment."},
{ch:1,type:'single',
 stem_zh:"CRISP-DM 中哪個階段最常被產業調查指出佔用最多時間？",
 stem_en:"Which CRISP-DM phase do industry surveys most often cite as the largest time-sink?",
 options_zh:["商業理解","資料準備","建模","部署"],
 options_en:["Business Understanding","Data Preparation","Modeling","Deployment"],
 answer:1,
 exp_zh:"多項業界調查指出資料準備（清理、整合、特徵工程）約佔專案 60–80% 時間，遠多於建模。",
 exp_en:"Surveys repeatedly report data preparation (cleaning, integration, feature engineering) consumes 60–80% of project time, far more than modeling."},
{ch:1,type:'single',
 stem_zh:"KDD 流程 (Fayyad 1996) 與 CRISP-DM 最主要的差別為何？",
 stem_en:"What is the main difference between the KDD process (Fayyad 1996) and CRISP-DM?",
 options_zh:["KDD 沒有評估步驟","CRISP-DM 加入了明確的『商業理解』與『部署』階段","KDD 是非迭代的","CRISP-DM 只用於監督式學習"],
 options_en:["KDD has no evaluation step","CRISP-DM adds explicit 'Business Understanding' and 'Deployment' phases","KDD is non-iterative","CRISP-DM is only for supervised learning"],
 answer:1,
 exp_zh:"CRISP-DM 在 KDD 的技術流程外，明確把商業理解與部署納入循環，反映業界專案的完整生命週期。",
 exp_en:"CRISP-DM augments KDD's technical pipeline by explicitly including Business Understanding and Deployment, reflecting industry project life-cycles."},
{ch:1,type:'single',
 stem_zh:"Eric Siegel 的 bizML 框架最強調哪一件事？",
 stem_en:"What does Eric Siegel's bizML framework most emphasize?",
 options_zh:["更先進的演算法","在開始建模前先嚴格定義業務預測目標","只用深度學習","完全自動化 AutoML"],
 options_en:["Using cutting-edge algorithms","Rigorously defining the business prediction goal before modeling","Using only deep learning","Full AutoML automation"],
 answer:1,
 exp_zh:"bizML（Siegel 2024）主張資料科學失敗最常因為沒先回答『要預測什麼、可以怎麼用』，而不是技術不夠。",
 exp_en:"bizML (Siegel 2024) argues data-science failures usually stem from skipping a precise prediction goal, not from inadequate algorithms."},
{ch:1,type:'single',
 stem_zh:"微軟 Team Data Science Process (TDSP) 相較 CRISP-DM 增加了哪一面向？",
 stem_en:"What aspect does Microsoft's Team Data Science Process (TDSP) add beyond CRISP-DM?",
 options_zh:["雲端基礎設施與團隊角色定義","只剩 3 個階段","以 SQL 為核心","禁止使用版本控制"],
 options_en:["Cloud infrastructure & team-role definitions","Only 3 phases","SQL-centric","Forbids version control"],
 answer:0,
 exp_zh:"TDSP 在 CRISP-DM 之上補上角色（PM/DS/DE）、Git 範本、Azure 雲端架構，更貼近現代團隊協作。",
 exp_en:"TDSP layers roles (PM/DS/DE), Git templates, and Azure cloud architecture on top of CRISP-DM for modern team workflows."},
{ch:1,type:'single',
 stem_zh:"下列何者最能反映『模型在實驗室高分但部署後失敗』的常見原因？",
 stem_en:"Which best describes the common cause of 'high lab metrics but failed deployment'?",
 options_zh:["訓練資料太大","模型未考慮資料漂移與部署環境","Python 版本不同","只用了一張 GPU"],
 options_en:["Training data too large","Model ignored data drift and deployment environment","Different Python version","Only used one GPU"],
 answer:1,
 exp_zh:"Data drift、target leakage、上線資料管線差異是部署失敗主因；CRISP-DM 的 Deployment 階段就是要正視這些。",
 exp_en:"Data drift, target leakage, and pipeline mismatches between training and production are the leading causes — Deployment exists to address them."},
{ch:1,type:'multi',
 stem_zh:"以下哪些是 CRISP-DM 的階段？(複選)",
 stem_en:"Which of the following are CRISP-DM phases? (multi-select)",
 options_zh:["商業理解","資料準備","部署","硬體採購"],
 options_en:["Business Understanding","Data Preparation","Deployment","Hardware Procurement"],
 answer:[0,1,2],
 exp_zh:"硬體採購不屬於 CRISP-DM 六個階段；其餘三項皆是。",
 exp_en:"Hardware procurement is not one of the 6 phases; the other three are."},
{ch:1,type:'multi',
 stem_zh:"以下哪些屬於『資料探勘』的典型任務？(複選)",
 stem_en:"Which are typical 'data mining' tasks? (multi-select)",
 options_zh:["分類","分群","關聯規則","資料庫備份"],
 options_en:["Classification","Clustering","Association rules","Database backup"],
 answer:[0,1,2],
 exp_zh:"資料探勘核心任務包含分類、回歸、分群、關聯規則、異常偵測等；資料庫備份是 IT 維運。",
 exp_en:"Core DM tasks include classification, regression, clustering, association rules, anomaly detection; database backup is IT ops."},
{ch:1,type:'tf',
 stem_zh:"CRISP-DM 是線性的瀑布流程，不允許階段間回溯。",
 stem_en:"CRISP-DM is a linear waterfall process and does not allow backtracking between phases.",
 answer:0,
 exp_zh:"錯。CRISP-DM 明示為循環迭代流程，原始圖即包含多條雙向箭頭。",
 exp_en:"False. CRISP-DM is explicitly iterative; the original diagram shows bidirectional arrows."},
{ch:1,type:'tf',
 stem_zh:"資料探勘最終的成功標準應該由商業目標而非僅以 accuracy 等技術指標決定。",
 stem_en:"Ultimate success of a data-mining project should be judged by business goals, not just technical metrics like accuracy.",
 answer:1,
 exp_zh:"對。CRISP-DM 評估階段強調回到商業理解的目標檢核，避免『高 accuracy 卻不解決問題』。",
 exp_en:"True. The Evaluation phase ties results back to business goals, avoiding 'high accuracy that solves nothing'."},

/* ========== Ch.2 資料準備與前處理 ========== */
{ch:2,type:'single',
 stem_zh:"下列何者為 MAR (Missing At Random) 的最佳描述？",
 stem_en:"Which best describes MAR (Missing At Random)?",
 options_zh:["缺失與資料本身或其他變數完全無關","缺失機率可由其他已觀察變數解釋","缺失機率依賴缺失值本身","缺失是系統性錯誤"],
 options_en:["Missingness is unrelated to any variable","Missingness probability is explainable by other observed variables","Missingness depends on the missing value itself","Missingness is a systematic error"],
 answer:1,
 exp_zh:"MCAR=完全隨機；MAR=條件於已觀察變數隨機；MNAR=與缺失值本身有關。",
 exp_en:"MCAR=completely random; MAR=random conditional on observed variables; MNAR=depends on the missing value itself."},
{ch:2,type:'single',
 stem_zh:"使用 SMOTE 進行類別不平衡處理時，最關鍵的『陷阱』是什麼？",
 stem_en:"What is the critical pitfall when using SMOTE for class imbalance?",
 options_zh:["SMOTE 不適用於 Python","必須在交叉驗證的訓練折內做，不能對整個資料先做再切","只能用於回歸","會降低 F1"],
 options_en:["SMOTE doesn't run in Python","Must be applied inside CV training folds, not on the whole dataset before splitting","Only for regression","Always lowers F1"],
 answer:1,
 exp_zh:"先 SMOTE 後切資料會讓合成的少數類樣本『洩漏』到驗證折，造成樂觀的評估偏差。",
 exp_en:"Applying SMOTE before splitting leaks synthetic minority samples into validation folds, inflating metrics."},
{ch:2,type:'single',
 stem_zh:"target leakage 最典型的例子是？",
 stem_en:"Which is the most typical example of target leakage?",
 options_zh:["使用未來才知道的資訊作為特徵","使用過多特徵","資料量太小","隨機種子未固定"],
 options_en:["Using information not available at prediction time as a feature","Using too many features","Dataset too small","Random seed not fixed"],
 answer:0,
 exp_zh:"任何只有在標籤已知後才能取得的資訊（例：診斷後的處置）若進入特徵，就會發生 target leakage。",
 exp_en:"Any feature available only after the label is known (e.g., post-diagnosis treatment) leaks the target."},
{ch:2,type:'single',
 stem_zh:"下列何者最不需要對數值特徵做標準化或縮放？",
 stem_en:"Which model is LEAST in need of feature scaling/standardization?",
 options_zh:["KNN","SVM (RBF)","Logistic Regression with L2","隨機森林"],
 options_en:["KNN","SVM (RBF)","Logistic Regression with L2","Random Forest"],
 answer:3,
 exp_zh:"基於距離或梯度的方法（KNN/SVM/帶正則的線性模型）對尺度敏感；樹模型只用閾值切割，不受尺度影響。",
 exp_en:"Distance- or gradient-based methods are scale-sensitive; tree models split on thresholds and are scale-invariant."},
{ch:2,type:'single',
 stem_zh:"One-Hot Encoding 相較 Target/Mean Encoding，最大的優點是？",
 stem_en:"What is One-Hot Encoding's main advantage over Target/Mean Encoding?",
 options_zh:["不會將目標訊息洩漏進特徵","維度更小","可保留順序","訓練更快"],
 options_en:["Does not leak target information into features","Lower dimensionality","Preserves ordering","Faster training"],
 answer:0,
 exp_zh:"Target encoding 把目標統計量寫進特徵，容易過擬合與洩漏；One-hot 不會，但對高基數欄位造成稀疏。",
 exp_en:"Target encoding writes target stats into features, risking leakage; one-hot is leakage-free but explodes dimensionality for high-cardinality fields."},
{ch:2,type:'single',
 stem_zh:"MICE (Multivariate Imputation by Chained Equations) 的核心想法為何？",
 stem_en:"What is the core idea of MICE (Multivariate Imputation by Chained Equations)?",
 options_zh:["以整體平均值填補","以鏈式回歸對每個含缺失欄位反覆估算","只在 MCAR 下可用","刪除所有缺失列"],
 options_en:["Fill with global mean","Iteratively regress each variable with missingness on others","Only valid under MCAR","Delete all rows with missing"],
 answer:1,
 exp_zh:"MICE 透過鏈式迭代，逐欄以其餘欄位回歸預測缺失值，可產生多重插補結果以反映不確定性。",
 exp_en:"MICE iterates column-by-column regressions on the others, producing multiple imputations that reflect uncertainty."},
{ch:2,type:'multi',
 stem_zh:"以下哪些屬於資料前處理的標準步驟？(複選)",
 stem_en:"Which are standard data-preprocessing steps? (multi-select)",
 options_zh:["缺失值處理","特徵縮放","類別編碼","選擇神經網路層數"],
 options_en:["Missing-value handling","Feature scaling","Categorical encoding","Choosing neural-network depth"],
 answer:[0,1,2],
 exp_zh:"神經網路架構選擇屬於建模階段；前三項屬於資料前處理。",
 exp_en:"NN architecture selection belongs to modeling; the first three are preprocessing."},
{ch:2,type:'multi',
 stem_zh:"下列哪些方法可用於緩解類別不平衡？(複選)",
 stem_en:"Which methods help mitigate class imbalance? (multi-select)",
 options_zh:["SMOTE 過取樣","欠取樣","class_weight 調整","刪除少數類樣本"],
 options_en:["SMOTE oversampling","Undersampling","class_weight adjustment","Dropping minority-class samples"],
 answer:[0,1,2],
 exp_zh:"刪除少數類只會更不平衡。SMOTE/欠取樣/class_weight 是常見手段。",
 exp_en:"Dropping minorities worsens imbalance. SMOTE, undersampling and class_weight are standard remedies."},
{ch:2,type:'tf',
 stem_zh:"對 LightGBM/XGBoost 等樹模型，數值特徵通常不需要標準化。",
 stem_en:"For tree models like LightGBM/XGBoost, numeric features generally do not need standardization.",
 answer:1,
 exp_zh:"對。樹模型以閾值切割，對尺度不敏感。",
 exp_en:"True. Tree models split by thresholds and are scale-invariant."},
{ch:2,type:'tf',
 stem_zh:"刪除有任何缺失的整列（complete-case）在 MNAR 下是安全且不偏的做法。",
 stem_en:"Listwise (complete-case) deletion is safe and unbiased under MNAR.",
 answer:0,
 exp_zh:"錯。MNAR 下任何刪除或單值填補都會偏差；需採模型化插補或敏感度分析。",
 exp_en:"False. Under MNAR any deletion or single-value imputation is biased; use model-based imputation or sensitivity analyses."},

/* ========== Ch.3 EDA 與視覺化 ========== */
{ch:3,type:'single',
 stem_zh:"Anscombe's quartet (1973) 想證明什麼？",
 stem_en:"What did Anscombe's quartet (1973) demonstrate?",
 options_zh:["相同統計摘要的資料集視覺化可能截然不同","散佈圖總比表格好","平均值不可靠","回歸係數不重要"],
 options_en:["Datasets with identical summary stats can look very different visually","Scatter plots always beat tables","Means are unreliable","Regression coefficients don't matter"],
 answer:0,
 exp_zh:"四組資料平均、方差、相關係數、回歸線幾乎相同，但散佈圖差異極大——可視化不可或缺。",
 exp_en:"Four datasets share nearly identical means, variances, correlations and regression lines, yet look completely different in scatter plots — visualization is indispensable."},
{ch:3,type:'single',
 stem_zh:"為何 matplotlib 將 viridis 作為預設 colormap？",
 stem_en:"Why does matplotlib use viridis as a default colormap?",
 options_zh:["顏色最鮮豔","感知均勻 (perceptually uniform) 且色盲友善","檔案最小","只能用於熱圖"],
 options_en:["Brightest colors","Perceptually uniform and colorblind-friendly","Smallest file size","Only works for heatmaps"],
 answer:1,
 exp_zh:"viridis (van der Walt & Smith 2015) 在亮度上呈單調遞增，色盲與灰階列印皆可辨識。",
 exp_en:"Viridis (van der Walt & Smith 2015) is monotonic in luminance and remains distinguishable in colorblind/grayscale settings."},
{ch:3,type:'single',
 stem_zh:"當散佈圖點數高達數百萬點導致『重疊塗黑』時，最合適的替代是？",
 stem_en:"When a scatter plot has millions of points and becomes a black blob, the best alternative is?",
 options_zh:["放大圖檔","改用 hexbin 或 2D 密度圖","切換成圓餅圖","增加 alpha"],
 options_en:["Enlarge the figure","Use hexbin or 2D density plot","Switch to pie chart","Increase alpha only"],
 answer:1,
 exp_zh:"hexbin / 2D KDE / datashader 把密度量化為色階，比單純調 alpha 更可靠地呈現大資料密度結構。",
 exp_en:"hexbin / 2D KDE / datashader bin density into color, more reliable than just alpha for large data."},
{ch:3,type:'single',
 stem_zh:"Tukey 1977《Exploratory Data Analysis》提出的箱形圖以哪 5 個數字為基礎？",
 stem_en:"Tukey's 1977 box plot is built from which five-number summary?",
 options_zh:["平均、中位數、眾數、最小、最大","最小、Q1、中位數、Q3、最大","平均、變異數、偏度、峰度、最大","Q1、Q2、Q3、Q4、Q5"],
 options_en:["Mean, median, mode, min, max","Min, Q1, Median, Q3, Max","Mean, var, skew, kurt, max","Q1, Q2, Q3, Q4, Q5"],
 answer:1,
 exp_zh:"五數摘要：min、Q1、median、Q3、max；異常點以 1.5×IQR 規則標示。",
 exp_en:"Five-number summary: min, Q1, median, Q3, max; outliers via the 1.5×IQR rule."},
{ch:3,type:'single',
 stem_zh:"相關係數熱圖選色時，最好使用？",
 stem_en:"When plotting a correlation heatmap, what palette should you choose?",
 options_zh:["連續單色（如 viridis）","發散型雙色（如 coolwarm，0 為中性）","隨機色票","只用紅色"],
 options_en:["Sequential single-hue (e.g., viridis)","Diverging two-hue (e.g., coolwarm centered at 0)","Random palette","Red only"],
 answer:1,
 exp_zh:"相關係數有正有負，發散型 colormap 以 0 為中心可同時編碼方向與強度。",
 exp_en:"Correlations are signed; a diverging colormap centered at 0 encodes both direction and magnitude."},
{ch:3,type:'single',
 stem_zh:"以下何者最不適合作為類別欄位的 EDA 圖？",
 stem_en:"Which plot is LEAST suitable for EDA of a categorical column?",
 options_zh:["長條圖","小提琴圖","堆疊長條圖","熱圖（與另一類別交叉）"],
 options_en:["Bar chart","Violin plot","Stacked bar","Heatmap (cross with another categorical)"],
 answer:1,
 exp_zh:"小提琴圖用於數值分布；類別最常用長條/堆疊長條或計數熱圖。",
 exp_en:"Violin plots show numeric distributions; categories use bar/stacked bar or count heatmaps."},
{ch:3,type:'multi',
 stem_zh:"以下哪些是良好 EDA 報告的特點？(複選)",
 stem_en:"Which are hallmarks of a good EDA report? (multi-select)",
 options_zh:["記錄缺失與異常","顯示分布與相關","附上對業務的觀察","只顯示模型 accuracy"],
 options_en:["Document missingness & anomalies","Show distributions & correlations","Add business observations","Only show model accuracy"],
 answer:[0,1,2],
 exp_zh:"EDA 目的是理解資料而非報模型分數；accuracy 屬於建模/評估產出。",
 exp_en:"EDA aims to understand the data, not report model scores; accuracy belongs to modeling/evaluation."},
{ch:3,type:'multi',
 stem_zh:"以下哪些是『誤導性可視化』的常見手法？(複選)",
 stem_en:"Which are common 'misleading visualization' tricks? (multi-select)",
 options_zh:["截斷 y 軸誇大差距","雙 y 軸混淆比較","3D 圓餅圖扭曲面積","使用感知均勻 colormap"],
 options_en:["Truncating y-axis to exaggerate","Dual y-axis confusing comparisons","3D pie distorting area","Using perceptually uniform colormap"],
 answer:[0,1,2],
 exp_zh:"感知均勻 colormap 是好習慣，其餘三項都是常見誤導手法。",
 exp_en:"Perceptually uniform colormaps are good practice; the other three are common deceptions."},
{ch:3,type:'tf',
 stem_zh:"皮爾遜相關係數為 0 即代表兩變數獨立。",
 stem_en:"A Pearson correlation of 0 implies the two variables are independent.",
 answer:0,
 exp_zh:"錯。Pearson 只衡量線性關係；非線性如 y=x² 可能 Pearson=0 但不獨立。",
 exp_en:"False. Pearson measures only linear association; nonlinear e.g. y=x² can have Pearson=0 yet not be independent."},
{ch:3,type:'tf',
 stem_zh:"EDA 階段發現的異常值應自動全部刪除以利後續建模。",
 stem_en:"Outliers found during EDA should always be automatically removed before modeling.",
 answer:0,
 exp_zh:"錯。異常值可能是錯誤、也可能是真實罕見事件（如詐欺、罕病）；要先判斷成因再處理。",
 exp_en:"False. Outliers may be errors or genuine rare events (fraud, rare disease); investigate cause before removing."},

/* ========== Ch.4 相似度與距離度量 ========== */
{ch:4,type:'single',
 stem_zh:"在高維空間中『所有點兩兩距離趨於相同』的現象稱為？",
 stem_en:"In high dimensions, the phenomenon that 'all pairwise distances become similar' is called?",
 options_zh:["維度詛咒","Hughes 現象","centrality bias","資料漂移"],
 options_en:["Curse of dimensionality","Hughes phenomenon","Centrality bias","Data drift"],
 answer:0,
 exp_zh:"維度詛咒 (Bellman 1961) 使 KNN、K-Means 等基於距離的演算法在高維下退化。",
 exp_en:"The curse of dimensionality (Bellman 1961) degrades distance-based algorithms like KNN and K-Means in high-D."},
{ch:4,type:'single',
 stem_zh:"想比較兩個文件的相似度（忽略長度差），最常用的度量是？",
 stem_en:"For comparing two documents' similarity (ignoring length), the most common measure is?",
 options_zh:["Euclidean","Cosine similarity","Manhattan","Hamming"],
 options_en:["Euclidean","Cosine similarity","Manhattan","Hamming"],
 answer:1,
 exp_zh:"Cosine 衡量向量夾角，與長度無關，是 TF-IDF/word embedding 標準度量。",
 exp_en:"Cosine measures angle, length-invariant — the standard for TF-IDF / word embeddings."},
{ch:4,type:'single',
 stem_zh:"比較兩集合（如使用者購物清單）的重疊度，最直接的度量是？",
 stem_en:"For overlap between two sets (e.g., user baskets), the most direct measure is?",
 options_zh:["Jaccard 指數","Cosine","Mahalanobis","DTW"],
 options_en:["Jaccard index","Cosine","Mahalanobis","DTW"],
 answer:0,
 exp_zh:"Jaccard = |A∩B| / |A∪B|，直接衡量兩集合重疊比例。",
 exp_en:"Jaccard = |A∩B|/|A∪B|, directly measuring set overlap."},
{ch:4,type:'single',
 stem_zh:"當特徵同時包含數值、類別、序位混合時，較合適的距離為？",
 stem_en:"When features mix numeric, categorical and ordinal, an appropriate distance is?",
 options_zh:["Euclidean","Mahalanobis","Gower distance","DTW"],
 options_en:["Euclidean","Mahalanobis","Gower distance","DTW"],
 answer:2,
 exp_zh:"Gower distance (Gower 1971) 為每種變數型別定義不同子距離再加權平均。",
 exp_en:"Gower distance (Gower 1971) defines per-variable-type sub-distances and averages them."},
{ch:4,type:'single',
 stem_zh:"比較兩條時序序列且容許時間軸彈性對齊，常用？",
 stem_en:"For comparing two time series with flexible time-axis alignment, use?",
 options_zh:["DTW (Dynamic Time Warping)","Cosine","Jaccard","Mahalanobis"],
 options_en:["DTW (Dynamic Time Warping)","Cosine","Jaccard","Mahalanobis"],
 answer:0,
 exp_zh:"DTW 允許時間軸非線性對齊，是時序分類/分群的標準度量。",
 exp_en:"DTW allows nonlinear time-axis alignment — standard for time-series classification/clustering."},
{ch:4,type:'single',
 stem_zh:"Manhattan 距離與 Euclidean 的差別最大表現在？",
 stem_en:"Manhattan vs. Euclidean distance most differ in?",
 options_zh:["低維時 Manhattan 較大","Manhattan 對單一維度大偏差更不敏感（總和 vs 平方）","Euclidean 不滿足三角不等式","Manhattan 不是 metric"],
 options_en:["Manhattan is larger in low-D","Manhattan is less sensitive to single-dimension large deviations (sum vs square)","Euclidean violates triangle inequality","Manhattan is not a metric"],
 answer:1,
 exp_zh:"Euclidean 對單一大偏差以平方放大；Manhattan 線性加總，對離群維度較穩。",
 exp_en:"Euclidean squares large deviations; Manhattan sums linearly and is more robust to outlier dimensions."},
{ch:4,type:'multi',
 stem_zh:"作為『度量 (metric)』必須滿足的性質有？(複選)",
 stem_en:"A function is a metric if it satisfies which? (multi-select)",
 options_zh:["非負性","對稱性","三角不等式","必為線性"],
 options_en:["Non-negativity","Symmetry","Triangle inequality","Must be linear"],
 answer:[0,1,2],
 exp_zh:"度量需滿足非負、d(x,x)=0、對稱、三角不等式；不要求線性。",
 exp_en:"A metric requires non-negativity, d(x,x)=0, symmetry, and triangle inequality; linearity is not required."},
{ch:4,type:'multi',
 stem_zh:"下列何者屬於高維資料中常見問題？(複選)",
 stem_en:"Which are common issues with high-dimensional data? (multi-select)",
 options_zh:["距離集中現象","資料稀疏","KNN 表現惡化","樹模型完全失效"],
 options_en:["Distance concentration","Data sparsity","KNN performance degrades","Tree models always fail"],
 answer:[0,1,2],
 exp_zh:"樹模型在高維仍可用（透過特徵選擇切割），未必失效；前三項皆為高維詛咒典型症狀。",
 exp_en:"Trees can still work in high-D via feature splits; the first three are textbook curse-of-dimensionality symptoms."},
{ch:4,type:'tf',
 stem_zh:"Cosine similarity 的值域為 [0, 1]。",
 stem_en:"Cosine similarity is bounded to [0, 1].",
 answer:0,
 exp_zh:"錯。Cosine similarity ∈ [−1, 1]；只有對非負向量（如 TF-IDF）才落在 [0, 1]。",
 exp_en:"False. Cosine similarity ∈ [−1, 1]; it only lies in [0, 1] for non-negative vectors (e.g., TF-IDF)."},
{ch:4,type:'tf',
 stem_zh:"Mahalanobis 距離會將特徵間的共變異結構納入考量。",
 stem_en:"Mahalanobis distance accounts for the covariance structure between features.",
 answer:1,
 exp_zh:"對。d_M(x,y)=√((x−y)ᵀΣ⁻¹(x−y))，以共變異反矩陣去除尺度與相關。",
 exp_en:"True. d_M(x,y)=√((x−y)ᵀΣ⁻¹(x−y)) — uses the inverse covariance to remove scale and correlations."},

/* ========== Ch.5 分類概論：KNN / Logistic ========== */
{ch:5,type:'single',
 stem_zh:"KNN 中 K 值取太小最容易導致？",
 stem_en:"In KNN, choosing K too small most often leads to?",
 options_zh:["欠擬合","過擬合與雜訊敏感","計算過慢","必為線性決策邊界"],
 options_en:["Underfitting","Overfitting and noise sensitivity","Too slow","Linear decision boundary"],
 answer:1,
 exp_zh:"K=1 完全跟隨訓練樣本噪聲；增加 K 會平滑邊界、提高偏差降低變異。",
 exp_en:"K=1 follows training-set noise; larger K smooths the boundary, increasing bias and reducing variance."},
{ch:5,type:'single',
 stem_zh:"Logistic Regression 中 sigmoid 函數的核心作用是？",
 stem_en:"In Logistic Regression, the core role of the sigmoid is to?",
 options_zh:["將線性 logit 轉為機率 (0,1)","加入非線性使其與神經網路同效","規範化權重","計算梯度"],
 options_en:["Map linear logit to probability in (0,1)","Add nonlinearity equivalent to a neural net","Regularize weights","Compute gradients"],
 answer:0,
 exp_zh:"σ(z)=1/(1+e⁻ᶻ) 把任意實值映射到 (0,1)，使線性 logit z=wᵀx+b 成為機率估計。",
 exp_en:"σ(z)=1/(1+e⁻ᶻ) maps real-valued logit z=wᵀx+b into (0,1) to estimate probability."},
{ch:5,type:'single',
 stem_zh:"odds 與 logit 的關係正確的是？",
 stem_en:"Which correctly relates odds and logit?",
 options_zh:["logit = log(odds)","odds = log(logit)","logit = exp(odds)","logit = 1 − odds"],
 options_en:["logit = log(odds)","odds = log(logit)","logit = exp(odds)","logit = 1 − odds"],
 answer:0,
 exp_zh:"odds = p/(1−p)；logit = log(odds)。Logistic 模型即對 logit 做線性回歸。",
 exp_en:"odds = p/(1−p); logit = log(odds). Logistic regression linearly models the logit."},
{ch:5,type:'single',
 stem_zh:"加入 L1 正則化最大的效果是？",
 stem_en:"The main effect of adding L1 regularization is?",
 options_zh:["產生稀疏解（特徵自動選擇）","加速收斂","保證凸性","使輸出機率更校準"],
 options_en:["Produce sparse solutions (auto feature selection)","Speed up convergence","Guarantee convexity","Better-calibrated probabilities"],
 answer:0,
 exp_zh:"L1 在最佳化路徑上會把不相關係數壓到 0，產生稀疏權重——LASSO 的精神。",
 exp_en:"L1 drives irrelevant coefficients exactly to 0, producing sparse weights — the LASSO idea."},
{ch:5,type:'single',
 stem_zh:"多類別分類常用 softmax，對應的損失函數通常是？",
 stem_en:"Multiclass classification commonly uses softmax with which loss?",
 options_zh:["Hinge loss","Cross-entropy","Squared error","Huber loss"],
 options_en:["Hinge loss","Cross-entropy","Squared error","Huber loss"],
 answer:1,
 exp_zh:"softmax + categorical cross-entropy 是多類別分類的標準組合。",
 exp_en:"softmax + categorical cross-entropy is the standard multiclass pair."},
{ch:5,type:'single',
 stem_zh:"線性 Logistic Regression 的決策邊界形狀是？",
 stem_en:"The decision boundary of plain Logistic Regression is?",
 options_zh:["超平面（線性）","球面","樹狀切分","任意非線性曲面"],
 options_en:["Hyperplane (linear)","Sphere","Tree-shaped splits","Arbitrary nonlinear surface"],
 answer:0,
 exp_zh:"沒有特徵變換時，Logistic Regression 等位面為 wᵀx+b=0 的超平面。",
 exp_en:"Without feature transforms, Logistic Regression's level set wᵀx+b=0 is a hyperplane."},
{ch:5,type:'multi',
 stem_zh:"以下哪些是 KNN 的特性？(複選)",
 stem_en:"Which are properties of KNN? (multi-select)",
 options_zh:["惰性學習 (lazy)","推論時計算成本高","對特徵尺度敏感","訓練時必學習權重向量"],
 options_en:["Lazy learning","High inference cost","Sensitive to feature scale","Learns a weight vector during training"],
 answer:[0,1,2],
 exp_zh:"KNN 不學模型；訓練只是儲存資料，所以推論慢；距離度量使其對尺度敏感。",
 exp_en:"KNN stores data instead of training a model; inference is costly; distance makes it scale-sensitive."},
{ch:5,type:'multi',
 stem_zh:"處理多類別 (multiclass) 的常見策略有？(複選)",
 stem_en:"Common strategies for multiclass classification include? (multi-select)",
 options_zh:["One-vs-Rest","One-vs-One","Softmax 多項式 Logistic","只能用 SVM"],
 options_en:["One-vs-Rest","One-vs-One","Softmax multinomial Logistic","Only SVM works"],
 answer:[0,1,2],
 exp_zh:"OvR、OvO、softmax 皆可；多類別不限於 SVM。",
 exp_en:"OvR, OvO, softmax all apply; multiclass is not limited to SVM."},
{ch:5,type:'tf',
 stem_zh:"KNN 必須在訓練資料上經過明確的迭代『學習參數』。",
 stem_en:"KNN must explicitly iterate over training data to 'learn parameters'.",
 answer:0,
 exp_zh:"錯。KNN 是 lazy learning，沒有顯式參數學習；只在推論時計算距離。",
 exp_en:"False. KNN is lazy — no parameter learning; only computes distances at inference."},
{ch:5,type:'tf',
 stem_zh:"Logistic Regression 雖名為『回歸』但實際上是分類模型。",
 stem_en:"Despite its name, Logistic Regression is a classification model.",
 answer:1,
 exp_zh:"對。它對 logit 做線性回歸，但輸出為類別機率，用於分類。",
 exp_en:"True. It linearly regresses the logit but outputs class probabilities for classification."},

/* ========== Ch.6 決策樹與隨機森林 ========== */
{ch:6,type:'single',
 stem_zh:"Gini 不純度 (impurity) 與 Entropy 比較，下列何者正確？",
 stem_en:"Comparing Gini impurity to Entropy, which is correct?",
 options_zh:["Gini 為熵的二階近似，計算較快","Gini 一定大於 Entropy","只有 ID3 使用 Gini","Entropy 不能用於分類樹"],
 options_en:["Gini is a 2nd-order approximation of entropy and is faster to compute","Gini is always larger than entropy","Only ID3 uses Gini","Entropy can't be used for classification trees"],
 answer:0,
 exp_zh:"Gini = 1−Σpᵢ²，是 −Σpᵢ log pᵢ 的二階泰勒近似；數值近似但避免 log 計算。",
 exp_en:"Gini = 1−Σpᵢ² is a 2nd-order Taylor approximation of entropy −Σpᵢ log pᵢ; similar but avoids the log."},
{ch:6,type:'single',
 stem_zh:"隨機森林 (Random Forest) 相對單棵樹的主要優勢是？",
 stem_en:"Random Forest's main advantage over a single tree is?",
 options_zh:["透過 bagging + 特徵抽樣降低變異","完全消除偏差","訓練更快","可保證解釋性"],
 options_en:["Bagging + feature subsampling reduces variance","Eliminates bias entirely","Faster training","Guarantees interpretability"],
 answer:0,
 exp_zh:"RF (Breiman 2001) 用 bootstrap 樣本 + 隨機特徵子集去相關各樹，主要降低變異而非偏差。",
 exp_en:"RF (Breiman 2001) decorrelates trees via bootstrap samples + random feature subsets, primarily reducing variance."},
{ch:6,type:'single',
 stem_zh:"梯度提升 (GBM) 每一輪新弱學習器擬合的是？",
 stem_en:"In gradient boosting (GBM), each new weak learner fits to?",
 options_zh:["原始標籤","當前模型的負梯度（殘差）","隨機噪聲","上一輪預測值"],
 options_en:["Original labels","The current model's negative gradient (residuals)","Random noise","The previous round's predictions"],
 answer:1,
 exp_zh:"GBM (Friedman 2001) 將提升視為梯度下降，每輪用弱學習器逼近損失負梯度。",
 exp_en:"GBM (Friedman 2001) treats boosting as gradient descent — each weak learner approximates the loss's negative gradient."},
{ch:6,type:'single',
 stem_zh:"XGBoost 2.x 對類別特徵的最大改進是？",
 stem_en:"XGBoost 2.x's biggest improvement for categorical features is?",
 options_zh:["完全禁用類別特徵","原生支援 categorical splits，無需事先 one-hot","只能透過 target encoding","僅限二元類別"],
 options_en:["Disables categorical features","Native categorical splits without pre one-hot","Only via target encoding","Binary categoricals only"],
 answer:1,
 exp_zh:"XGBoost 2.x 起原生支援 categorical 切分（類似 LightGBM），免去 one-hot 維度爆炸。",
 exp_en:"From XGBoost 2.x, native categorical splits (à la LightGBM) avoid one-hot dimensionality blow-up."},
{ch:6,type:'single',
 stem_zh:"LightGBM 與 XGBoost 在樹生長策略最大差異是？",
 stem_en:"The biggest difference in tree-growth strategy between LightGBM and XGBoost is?",
 options_zh:["LightGBM 為 leaf-wise（深度優先），XGBoost 預設 level-wise（廣度優先）","兩者完全相同","XGBoost 不支援 GPU","LightGBM 只能跑分類"],
 options_en:["LightGBM grows leaf-wise (depth-first); XGBoost defaults to level-wise (breadth-first)","Identical","XGBoost has no GPU","LightGBM only classification"],
 answer:0,
 exp_zh:"LightGBM leaf-wise 通常更快收斂且精度更高，但更易過擬合，需控制 num_leaves。",
 exp_en:"LightGBM's leaf-wise growth often converges faster with higher accuracy but overfits more easily, so control num_leaves."},
{ch:6,type:'single',
 stem_zh:"下列何者最不適合用『特徵重要性 (mean decrease in impurity)』直接解讀？",
 stem_en:"Which is LEAST appropriate to interpret via 'mean decrease in impurity' feature importance?",
 options_zh:["全為連續且尺度相近的數值特徵","包含高基數類別欄位","完全二元特徵","所有特徵獨立"],
 options_en:["All continuous features at similar scale","Including high-cardinality categorical fields","All binary features","All features independent"],
 answer:1,
 exp_zh:"MDI 偏好可切分點多的高基數欄位，易造成虛假重要性，建議改用 permutation importance。",
 exp_en:"MDI is biased toward high-cardinality features with many split points; prefer permutation importance."},
{ch:6,type:'multi',
 stem_zh:"以下哪些是樹模型（單棵）的優點？(複選)",
 stem_en:"Which are advantages of (single) decision trees? (multi-select)",
 options_zh:["可解釋性高","可處理數值與類別","對特徵尺度不敏感","在小資料上一般優於線性模型"],
 options_en:["High interpretability","Handles numeric & categorical","Scale-invariant","Always beats linear models on small data"],
 answer:[0,1,2],
 exp_zh:"小資料上線性/正則化模型常勝；單樹易過擬合。前三項是樹的本質優勢。",
 exp_en:"On small data, regularized linear models often win; single trees overfit. The first three are tree advantages."},
{ch:6,type:'multi',
 stem_zh:"以下哪些屬於現代主流梯度提升庫？(複選)",
 stem_en:"Which are mainstream modern gradient-boosting libraries? (multi-select)",
 options_zh:["XGBoost","LightGBM","CatBoost","RandomNet"],
 options_en:["XGBoost","LightGBM","CatBoost","RandomNet"],
 answer:[0,1,2],
 exp_zh:"XGBoost、LightGBM、CatBoost 是三大主流；RandomNet 不存在。",
 exp_en:"XGBoost, LightGBM, CatBoost are the big three; RandomNet is not a real library."},
{ch:6,type:'tf',
 stem_zh:"隨機森林的『隨機』來自 bootstrap 樣本與隨機特徵子集兩部分。",
 stem_en:"The 'random' in Random Forest comes from both bootstrap sampling and random feature subsets.",
 answer:1,
 exp_zh:"對。兩層隨機性使各樹去相關，是降變異的關鍵。",
 exp_en:"True. Two layers of randomness decorrelate trees — the key to variance reduction."},
{ch:6,type:'tf',
 stem_zh:"GBM 比 RF 更易過擬合，所以幾乎不需要早停或 learning rate 調整。",
 stem_en:"GBM overfits more easily than RF, so it rarely needs early stopping or learning-rate tuning.",
 answer:0,
 exp_zh:"錯。正因為 GBM 易過擬合，learning rate、樹數、早停（如 XGBoost early_stopping_rounds）反而更重要。",
 exp_en:"False. Because GBM overfits, learning rate, n_estimators and early stopping are even more crucial."},

/* ========== Ch.7 樸素貝氏與 SVM ========== */
{ch:7,type:'single',
 stem_zh:"樸素貝氏 (Naive Bayes) 的核心假設是？",
 stem_en:"The core assumption of Naive Bayes is?",
 options_zh:["特徵服從常態分布","特徵在給定類別下條件獨立","訓練資料無噪聲","特徵之間嚴格相關"],
 options_en:["Features are normally distributed","Features are conditionally independent given the class","Training data is noise-free","Features are strictly correlated"],
 answer:1,
 exp_zh:"NB 假設 P(x|y)=∏P(xᵢ|y)，即條件獨立——雖『天真』但在文本分類表現意外地好。",
 exp_en:"NB assumes P(x|y)=∏P(xᵢ|y) (conditional independence) — naive but surprisingly effective for text."},
{ch:7,type:'single',
 stem_zh:"Laplace (add-one) smoothing 解決的問題是？",
 stem_en:"Laplace (add-one) smoothing solves what problem?",
 options_zh:["過擬合","測試時遇到未見過的特徵值導致機率為 0","訓練太慢","資料不平衡"],
 options_en:["Overfitting","Zero-probability for unseen feature values at test time","Slow training","Class imbalance"],
 answer:1,
 exp_zh:"未見過的詞會讓 P(x|y)=0 拖垮整個乘積；Laplace 在分子分母都加常數避免此問題。",
 exp_en:"Unseen tokens cause P(x|y)=0 and zero-out the product; Laplace adds a constant to numerator/denominator."},
{ch:7,type:'single',
 stem_zh:"SVM 的『最大間隔 (max margin)』指的是？",
 stem_en:"SVM's 'maximum margin' refers to?",
 options_zh:["訓練樣本到決策邊界的最小距離最大化","訓練誤差最小化","所有點到原點的最大距離","kernel 函數的最大值"],
 options_en:["Maximizing the minimum distance from training points to the boundary","Minimizing training error","Maximum distance to origin","Maximum of the kernel function"],
 answer:0,
 exp_zh:"SVM 在線性可分時尋找使最近樣本到超平面距離最大的決策邊界。",
 exp_en:"SVM finds the boundary that maximizes the distance to the nearest training sample (the margin)."},
{ch:7,type:'single',
 stem_zh:"kernel trick 的本質是？",
 stem_en:"The essence of the kernel trick is?",
 options_zh:["在不顯式映射的情況下計算高維內積","用神經網路替代 SVM","只能用 RBF kernel","降維到 2D"],
 options_en:["Compute high-dimensional inner products without explicit mapping","Replace SVM with neural nets","Only RBF kernel","Reduce to 2D"],
 answer:0,
 exp_zh:"以核函數 K(x,y)=φ(x)·φ(y) 在不計算 φ 的情況下取得高維內積，避免維度爆炸。",
 exp_en:"K(x,y)=φ(x)·φ(y) yields a high-dimensional inner product without computing φ — sidestepping dimensionality."},
{ch:7,type:'single',
 stem_zh:"SVM 中參數 C 變大時，模型行為傾向？",
 stem_en:"When SVM's parameter C is increased, the model tends to?",
 options_zh:["更容忍誤分（軟間隔變大）","更不容忍誤分（硬間隔），更易過擬合","完全等同 Logistic","必為線性"],
 options_en:["Tolerate more misclassifications (wider soft margin)","Tolerate fewer misclassifications (harder margin), more prone to overfit","Identical to Logistic","Forced linear"],
 answer:1,
 exp_zh:"C 大 → 對誤分懲罰大 → 邊界更貼合資料 → 變異增加（易過擬合）。",
 exp_en:"Large C heavily penalizes errors → tighter fit → higher variance / overfit risk."},
{ch:7,type:'single',
 stem_zh:"RBF kernel 中 gamma 參數的作用是？",
 stem_en:"In an RBF kernel, the gamma parameter controls?",
 options_zh:["決策邊界的彎曲度（單點影響範圍倒數）","樣本權重","資料尺度","支持向量數量"],
 options_en:["Decision boundary curvature (inverse of a point's influence range)","Sample weight","Data scale","Number of support vectors"],
 answer:0,
 exp_zh:"gamma 大 → 每點影響範圍小 → 邊界更曲折、易過擬合；gamma 小 → 平滑邊界。",
 exp_en:"Large gamma → narrow influence per point → wigglier boundary, overfit risk; small gamma → smoother."},
{ch:7,type:'multi',
 stem_zh:"以下哪些是 SVM 的優點？(複選)",
 stem_en:"Which are SVM advantages? (multi-select)",
 options_zh:["可透過 kernel 處理非線性","在高維、小樣本表現良好","僅由支持向量決定模型","在百萬樣本上幾乎總是最快"],
 options_en:["Handles nonlinearity via kernels","Works well in high-D / small-sample","Defined by support vectors only","Always fastest on millions of samples"],
 answer:[0,1,2],
 exp_zh:"SVM 在超大樣本下訓練 O(n²~n³) 不利於 scale；前三項為其優勢。",
 exp_en:"SVM training is O(n²~n³) and scales poorly to huge n; the first three are real strengths."},
{ch:7,type:'multi',
 stem_zh:"以下哪些是常見的 SVM 核函數？(複選)",
 stem_en:"Which are common SVM kernels? (multi-select)",
 options_zh:["Linear","Polynomial","RBF (Gaussian)","Newton"],
 options_en:["Linear","Polynomial","RBF (Gaussian)","Newton"],
 answer:[0,1,2],
 exp_zh:"Linear、Polynomial、RBF、Sigmoid 為標準核；Newton 是最佳化方法不是核。",
 exp_en:"Linear, Polynomial, RBF, Sigmoid are standard kernels; Newton is an optimization method, not a kernel."},
{ch:7,type:'tf',
 stem_zh:"樸素貝氏即使條件獨立假設不嚴格成立，仍可能在文本分類上有實用表現。",
 stem_en:"Naive Bayes can still perform well on text classification even when conditional independence does not strictly hold.",
 answer:1,
 exp_zh:"對。NB 的決策邊界相對穩健；只要排名正確即可分類，不需要校準完美的機率。",
 exp_en:"True. NB's decision boundary is robust — accurate ranking suffices for classification even if probabilities aren't calibrated."},
{ch:7,type:'tf',
 stem_zh:"線性 SVM 對非線性可分資料總能透過增加 C 完全分對。",
 stem_en:"A linear SVM can always perfectly separate nonlinearly separable data by increasing C.",
 answer:0,
 exp_zh:"錯。非線性問題需要 kernel；單靠 C 不能克服資料本身的非線性結構。",
 exp_en:"False. Nonlinear data require a kernel; tuning C alone cannot overcome inherent nonlinearity."},

/* ========== Ch.8 模型評估與調參 ========== */
{ch:8,type:'single',
 stem_zh:"類別嚴重不平衡（例：1% 陽性）時，相較 ROC-AUC 更適合的指標是？",
 stem_en:"For severe class imbalance (e.g., 1% positives), which metric is preferred over ROC-AUC?",
 options_zh:["Precision-Recall AUC","Accuracy","R²","MSE"],
 options_en:["Precision-Recall AUC","Accuracy","R²","MSE"],
 answer:0,
 exp_zh:"嚴重不平衡時 ROC 易過度樂觀；PR 曲線只看陽性檢出，較反映實際品質。",
 exp_en:"Under heavy imbalance, ROC can be overly optimistic; PR focuses on positive-class quality."},
{ch:8,type:'single',
 stem_zh:"nested cross-validation 主要解決什麼問題？",
 stem_en:"Nested cross-validation primarily addresses?",
 options_zh:["GPU 不足","超參數選擇與效能估計同時可靠","資料缺失","加快訓練"],
 options_en:["Insufficient GPU","Reliable hyperparameter selection and performance estimate simultaneously","Missing data","Faster training"],
 answer:1,
 exp_zh:"外層估計泛化效能、內層調參，避免『同一折同時調參+估計』造成的樂觀偏差 (Cawley & Talbot 2010)。",
 exp_en:"Outer loop estimates generalization; inner loop tunes — avoids the optimistic bias from tuning and estimating on the same fold (Cawley & Talbot 2010)."},
{ch:8,type:'single',
 stem_zh:"在類別不平衡的二分類，分層交叉驗證 (stratified CV) 的主要好處是？",
 stem_en:"In imbalanced binary classification, stratified CV mainly?",
 options_zh:["每折類別比例與整體一致，降低折間方差","加快計算","保證樣本獨立","解決資料漂移"],
 options_en:["Keeps class ratio per fold the same as overall, reducing fold variance","Faster compute","Guarantees independence","Solves data drift"],
 answer:0,
 exp_zh:"分層保證每折正/負比例一致，使效能估計更穩定。",
 exp_en:"Stratification preserves per-fold class ratios, stabilizing performance estimates."},
{ch:8,type:'single',
 stem_zh:"Brier score 用於評估什麼？",
 stem_en:"Brier score evaluates what?",
 options_zh:["分類的機率預測校準","回歸的 R²","分群的純度","關聯規則的 lift"],
 options_en:["Calibration of classifier probability predictions","Regression R²","Cluster purity","Association lift"],
 answer:0,
 exp_zh:"Brier = 平均 (p − y)²，越小越好；可分解為校準與分辨率兩部分。",
 exp_en:"Brier = mean (p − y)², lower is better; decomposes into calibration and refinement."},
{ch:8,type:'single',
 stem_zh:"Platt scaling 與 isotonic regression 都用於？",
 stem_en:"Platt scaling and isotonic regression are both used for?",
 options_zh:["機率校準","特徵選擇","資料增強","資料庫索引"],
 options_en:["Probability calibration","Feature selection","Data augmentation","Database indexing"],
 answer:0,
 exp_zh:"兩者皆為事後 (post-hoc) 機率校準法：Platt 假設 sigmoid，isotonic 為非參數單調。",
 exp_en:"Both are post-hoc probability calibrators: Platt assumes sigmoid; isotonic is nonparametric and monotone."},
{ch:8,type:'single',
 stem_zh:"Optuna 的 MedianPruner 屬於哪一類最佳化技巧？",
 stem_en:"Optuna's MedianPruner is what kind of optimization technique?",
 options_zh:["早期終止 (pruning) 表現差的試驗","隨機搜尋","遺傳演算法","網格搜尋"],
 options_en:["Early termination (pruning) of poor trials","Random search","Genetic algorithm","Grid search"],
 answer:0,
 exp_zh:"Pruner 在訓練中監測中間指標，若明顯落後中位數即提早停止，省下計算資源。",
 exp_en:"A pruner monitors intermediate metrics; if a trial lags the median significantly, it's stopped early to save compute."},
{ch:8,type:'multi',
 stem_zh:"以下哪些指標可用於二分類？(複選)",
 stem_en:"Which metrics apply to binary classification? (multi-select)",
 options_zh:["Precision","Recall","F1","R²"],
 options_en:["Precision","Recall","F1","R²"],
 answer:[0,1,2],
 exp_zh:"R² 是回歸指標；前三項為標準分類指標。",
 exp_en:"R² is for regression; the first three are standard classification metrics."},
{ch:8,type:'multi',
 stem_zh:"以下哪些是超參數搜尋策略？(複選)",
 stem_en:"Which are hyperparameter-search strategies? (multi-select)",
 options_zh:["Grid search","Random search","Bayesian optimization (TPE/GP)","梯度下降找最佳 learning rate 的訓練本身"],
 options_en:["Grid search","Random search","Bayesian optimization (TPE/GP)","Training itself by gradient descent"],
 answer:[0,1,2],
 exp_zh:"訓練時的梯度下降是學參數而非超參數；前三項為超參數搜尋。",
 exp_en:"Gradient descent during training learns parameters, not hyperparameters; the first three are HP-search."},
{ch:8,type:'tf',
 stem_zh:"在資料切分前對全資料做特徵選擇，再做 CV 是公平的評估方式。",
 stem_en:"Doing feature selection on the whole dataset before CV is a fair evaluation.",
 answer:0,
 exp_zh:"錯。會導致目標洩漏；特徵選擇須包在 CV 折內。",
 exp_en:"False. It leaks the target; feature selection must be inside the CV folds."},
{ch:8,type:'tf',
 stem_zh:"模型在驗證集上 AUC 高，並不能保證部署後仍維持相同表現。",
 stem_en:"High validation AUC does not guarantee the same performance after deployment.",
 answer:1,
 exp_zh:"對。資料漂移、人口差異、上線管線差別都可能讓線上 AUC 顯著下滑。",
 exp_en:"True. Data drift, demographic shift, or pipeline differences can drop online AUC significantly."},

/* ========== Ch.9 K-Means 與階層分群 ========== */
{ch:9,type:'single',
 stem_zh:"K-Means 標準演算法 (Lloyd's) 每輪交替執行哪兩步？",
 stem_en:"Standard K-Means (Lloyd's) alternates which two steps?",
 options_zh:["分配 (assign) 與更新 (update)","切分與合併","隨機抽樣與梯度下降","採樣與排序"],
 options_en:["Assign and update","Split and merge","Sample and gradient descent","Sample and sort"],
 answer:0,
 exp_zh:"每點分配到最近中心 (assign)；再以各群均值更新中心 (update)。",
 exp_en:"Assign each point to its nearest centroid, then update centroids as cluster means."},
{ch:9,type:'single',
 stem_zh:"k-means++ 的初始化策略主要優於隨機初始化的點在？",
 stem_en:"k-means++ initialization beats random init mainly because?",
 options_zh:["以與已選中心成反比的距離機率挑選新中心，加速收斂並降低劣局風險","完全隨機","只選最遠點","由使用者手動指定"],
 options_en:["Picks new centers with probability proportional to squared distance from existing ones, speeding convergence and avoiding bad local optima","Pure random","Always picks farthest","User-specified manually"],
 answer:0,
 exp_zh:"k-means++ (Arthur & Vassilvitskii 2007) 用 D² 加權挑點，比純隨機更穩定。",
 exp_en:"k-means++ (Arthur & Vassilvitskii 2007) samples by D² weighting — more stable than pure random."},
{ch:9,type:'single',
 stem_zh:"判斷 K-Means 最佳 K 值時，elbow 與 silhouette 兩種方法的差別是？",
 stem_en:"For choosing K in K-Means, how do elbow and silhouette methods differ?",
 options_zh:["elbow 看 inertia 拐點較主觀，silhouette 量化群內凝聚與群間分離","二者完全等同","silhouette 只能用於回歸","elbow 需要 PCA"],
 options_en:["Elbow inspects inertia 'knee' (subjective); silhouette quantifies cohesion vs separation","Identical","Silhouette is for regression","Elbow needs PCA"],
 answer:0,
 exp_zh:"silhouette ∈ [−1,1]，越接近 1 越好；對挑 K 比 elbow 更客觀。",
 exp_en:"Silhouette ∈ [−1,1], higher is better — more objective than the visual elbow."},
{ch:9,type:'single',
 stem_zh:"Ward linkage 的合併準則是？",
 stem_en:"Ward linkage's merge criterion is?",
 options_zh:["最小化合併後總群內平方和增量","最小化群間中心距離","最大化群間距離","隨機合併"],
 options_en:["Minimize the increase in total within-cluster sum of squares after merging","Minimize centroid distance","Maximize between-cluster distance","Random merge"],
 answer:0,
 exp_zh:"Ward 1963 每步選擇使 ΣSSE 增量最小的兩群合併，傾向產生大小相近的群。",
 exp_en:"Ward (1963) merges the two clusters whose merger causes the smallest increase in total SSE, favoring balanced sizes."},
{ch:9,type:'single',
 stem_zh:"看 dendrogram 決定群數時的常見做法是？",
 stem_en:"To decide cluster count from a dendrogram, one commonly?",
 options_zh:["在最長未被穿越的垂直距離處橫切","切在最短距離","只看葉節點數量","隨機選一刀"],
 options_en:["Cut across the longest vertical distance not crossed by a merge","Cut at the smallest distance","Count leaves only","Cut randomly"],
 answer:0,
 exp_zh:"最大『無合併垂直空隙』暗示在那個高度將資料分成的群最穩定。",
 exp_en:"The largest 'merge-free vertical gap' suggests the most stable cluster count at that height."},
{ch:9,type:'single',
 stem_zh:"K-Means 對下列哪一種分布最不友善？",
 stem_en:"K-Means is LEAST friendly to which distribution?",
 options_zh:["球形等變異","非凸形（如月牙）","大小相當的高斯堆","二元混合"],
 options_en:["Spherical with equal variance","Non-convex (e.g., crescent)","Equal-size Gaussian blobs","Mixture of two clusters"],
 answer:1,
 exp_zh:"K-Means 假設凸的等變異群；非凸結構（月牙、環狀）需用 DBSCAN/Spectral。",
 exp_en:"K-Means assumes convex equal-variance clusters; non-convex shapes (moons, rings) need DBSCAN/Spectral."},
{ch:9,type:'multi',
 stem_zh:"以下哪些是 K-Means 的限制？(複選)",
 stem_en:"Which are limitations of K-Means? (multi-select)",
 options_zh:["需指定 K","對初始化敏感","只擅長凸形等變異群","必為非監督評估"],
 options_en:["Requires K","Initialization-sensitive","Only handles convex equal-variance clusters","Must be unsupervised evaluation"],
 answer:[0,1,2],
 exp_zh:"前三項為 K-Means 經典缺點；最後一項與分群是否合適無關。",
 exp_en:"First three are classic K-Means flaws; the last isn't about K-Means itself."},
{ch:9,type:'multi',
 stem_zh:"以下哪些是常見的階層分群連結方式？(複選)",
 stem_en:"Which are common hierarchical-clustering linkages? (multi-select)",
 options_zh:["single","complete","average","gini"],
 options_en:["single","complete","average","gini"],
 answer:[0,1,2],
 exp_zh:"single / complete / average / Ward 是標準 linkage；gini 是樹模型純度，不是 linkage。",
 exp_en:"single / complete / average / Ward are standard linkages; gini is a tree impurity, not a linkage."},
{ch:9,type:'tf',
 stem_zh:"K-Means 一定能收斂到全域最佳解。",
 stem_en:"K-Means always converges to the global optimum.",
 answer:0,
 exp_zh:"錯。K-Means 只保證收斂到區域最佳；不同初始化可能得到不同解。",
 exp_en:"False. K-Means converges only to a local optimum; different inits give different solutions."},
{ch:9,type:'tf',
 stem_zh:"silhouette 值越接近 1 表示分群結構越清晰。",
 stem_en:"Silhouette scores closer to 1 indicate clearer clustering structure.",
 answer:1,
 exp_zh:"對。silhouette s=(b−a)/max(a,b)，接近 1 表示群內緊湊、群間分離良好。",
 exp_en:"True. s=(b−a)/max(a,b); near 1 means tight cohesion and good separation."},

/* ========== Ch.10 密度型分群 (DBSCAN/HDBSCAN) ========== */
{ch:10,type:'single',
 stem_zh:"DBSCAN 中 core point 的定義是？",
 stem_en:"In DBSCAN, a core point is defined as?",
 options_zh:["在 eps 半徑內至少包含 minPts 個鄰居","距離原點最近的點","出現次數最多","樣本平均"],
 options_en:["A point with at least minPts neighbors within radius eps","Closest to origin","Most frequent","Sample mean"],
 answer:0,
 exp_zh:"core = |N_eps(p)| ≥ minPts；border = 在某 core 的鄰居但本身非 core；其餘為 noise。",
 exp_en:"core = |N_eps(p)| ≥ minPts; border = within some core's neighborhood but not core; rest is noise."},
{ch:10,type:'single',
 stem_zh:"DBSCAN 中 eps 太大會導致？",
 stem_en:"In DBSCAN, eps that is too large leads to?",
 options_zh:["所有點被視為雜訊","不同自然群被合併為一群","只剩兩群","完全等同 K-Means"],
 options_en:["All points become noise","Distinct natural clusters merge","Only two clusters remain","Same as K-Means"],
 answer:1,
 exp_zh:"eps 越大鄰居越多，原本分離的群會被連通成一群；過小則大多點變雜訊。",
 exp_en:"Large eps connects unrelated clusters; too small turns most points into noise."},
{ch:10,type:'single',
 stem_zh:"挑選 DBSCAN 的 eps 常用方法是？",
 stem_en:"A common method to pick DBSCAN's eps is?",
 options_zh:["看 k-distance plot 的拐點 (knee)","隨機嘗試","等於資料平均距離","固定 1.0"],
 options_en:["Inspect the knee of the k-distance plot","Random trial","Equal to mean pairwise distance","Fixed 1.0"],
 answer:0,
 exp_zh:"Ester 1996 建議：對每點計算其第 k 近鄰距離（k=minPts），排序後找拐點即為 eps 候選。",
 exp_en:"Ester (1996): sort the k-th nearest-neighbor distance for each point and read eps at the curve's knee."},
{ch:10,type:'single',
 stem_zh:"OPTICS 相對 DBSCAN 的主要優點是？",
 stem_en:"OPTICS's main advantage over DBSCAN is?",
 options_zh:["不需單一 eps，可呈現多尺度的可達性結構","收斂更快","只支援低維","不需 minPts"],
 options_en:["No single eps needed — exposes multi-scale reachability","Faster","Low-D only","No minPts"],
 answer:0,
 exp_zh:"OPTICS 產生 reachability plot，使用者可在多個密度尺度下擷取群結構。",
 exp_en:"OPTICS yields a reachability plot, exposing clusters at multiple density scales."},
{ch:10,type:'single',
 stem_zh:"HDBSCAN 相對 DBSCAN 的核心改進是？",
 stem_en:"HDBSCAN's core improvement over DBSCAN is?",
 options_zh:["可處理不同密度的群","完全去除雜訊點","必為球形群","僅支援大資料"],
 options_en:["Handles clusters of varying density","Removes all noise","Spherical clusters only","Big-data only"],
 answer:0,
 exp_zh:"HDBSCAN 透過密度層級樹擷取穩定群，能適應密度差異大的資料。",
 exp_en:"HDBSCAN builds a density hierarchy and extracts stable clusters, adapting to varying densities."},
{ch:10,type:'single',
 stem_zh:"GMM (Gaussian Mixture Model) 與 K-Means 最大差異是？",
 stem_en:"GMM's biggest difference from K-Means is?",
 options_zh:["GMM 提供軟分群（後驗機率）與橢圓型群","只能處理 2D","不用 EM","必為球形"],
 options_en:["GMM provides soft assignments (posterior) and ellipsoidal clusters","2D only","Doesn't use EM","Must be spherical"],
 answer:0,
 exp_zh:"GMM 用 EM 學習各成分的均值、共變異與混合權重，能擬合橢圓並提供軟分群。",
 exp_en:"GMM uses EM to fit means, covariances and weights — yielding ellipsoidal clusters and soft assignments."},
{ch:10,type:'multi',
 stem_zh:"DBSCAN 的優點有？(複選)",
 stem_en:"DBSCAN advantages include? (multi-select)",
 options_zh:["可發現任意形狀群","可自動辨識雜訊","不需事先指定 K","完全不需參數"],
 options_en:["Discovers arbitrary cluster shapes","Identifies noise","No need to specify K","No parameters at all"],
 answer:[0,1,2],
 exp_zh:"DBSCAN 仍需 eps 與 minPts；前三項是其經典優勢。",
 exp_en:"DBSCAN still needs eps and minPts; the first three are its classic advantages."},
{ch:10,type:'multi',
 stem_zh:"GMM 使用 EM 演算法的兩步驟為？(複選)",
 stem_en:"EM in GMM consists of which two steps? (multi-select)",
 options_zh:["E 步：計算後驗責任","M 步：更新參數","B 步：bootstrap","S 步：sort"],
 options_en:["E-step: compute responsibilities","M-step: update parameters","B-step: bootstrap","S-step: sort"],
 answer:[0,1],
 exp_zh:"EM = Expectation (E) + Maximization (M)；其餘為干擾項。",
 exp_en:"EM = Expectation + Maximization; others are distractors."},
{ch:10,type:'tf',
 stem_zh:"DBSCAN 不需要指定群數 K。",
 stem_en:"DBSCAN does not require specifying the number of clusters K.",
 answer:1,
 exp_zh:"對。群數由密度連通性自然決定。",
 exp_en:"True. The number of clusters emerges from density connectivity."},
{ch:10,type:'tf',
 stem_zh:"HDBSCAN 完全沒有任何雜訊點（noise），所有點必被分到某群。",
 stem_en:"HDBSCAN labels no point as noise; every point goes to a cluster.",
 answer:0,
 exp_zh:"錯。HDBSCAN 仍會將不夠穩定的點標為 noise（label = −1）。",
 exp_en:"False. HDBSCAN still labels unstable points as noise (label = −1)."},

/* ========== Ch.11 關聯規則 (Apriori/FP-Growth) ========== */
{ch:11,type:'single',
 stem_zh:"關聯規則 X ⇒ Y 的 confidence 定義是？",
 stem_en:"For rule X ⇒ Y, confidence is defined as?",
 options_zh:["P(X∪Y)","P(Y|X)","P(X)·P(Y)","P(X∩Y)/P(Y)"],
 options_en:["P(X∪Y)","P(Y|X)","P(X)·P(Y)","P(X∩Y)/P(Y)"],
 answer:1,
 exp_zh:"confidence(X⇒Y) = support(X∪Y)/support(X) = P(Y|X)。",
 exp_en:"confidence(X⇒Y) = support(X∪Y)/support(X) = P(Y|X)."},
{ch:11,type:'single',
 stem_zh:"lift = 1 表示？",
 stem_en:"lift = 1 means?",
 options_zh:["X 與 Y 完全相關","X 與 Y 獨立","規則無效","規則最佳"],
 options_en:["X and Y fully correlated","X and Y independent","Rule invalid","Best rule"],
 answer:1,
 exp_zh:"lift = confidence(X⇒Y)/support(Y)；= 1 即 P(Y|X)=P(Y)，X 與 Y 獨立。",
 exp_en:"lift = confidence(X⇒Y)/support(Y); =1 ↔ P(Y|X)=P(Y), independence."},
{ch:11,type:'single',
 stem_zh:"Apriori 屬性 (Apriori property) 指的是？",
 stem_en:"The Apriori property states that?",
 options_zh:["頻繁項集的所有子集亦為頻繁","不頻繁項集的所有超集亦不頻繁","支持度越高 lift 越高","規則越長越好"],
 options_en:["Subsets of a frequent itemset are also frequent","Supersets of an infrequent itemset are also infrequent","Higher support ⇒ higher lift","Longer rules are better"],
 answer:1,
 exp_zh:"兩種等價描述。Agrawal & Srikant 1994 利用此性質剪枝，避免列舉指數級候選。",
 exp_en:"Two equivalent statements; Agrawal & Srikant (1994) use this for pruning to avoid exponential candidate enumeration."},
{ch:11,type:'single',
 stem_zh:"FP-Growth 相對 Apriori 主要的優勢是？",
 stem_en:"FP-Growth's main advantage over Apriori is?",
 options_zh:["以 FP-tree 緊湊表示交易，避免多次掃描與候選生成","必為遞迴","只能在小資料上跑","結果不同"],
 options_en:["Compact FP-tree representation avoids multiple scans and candidate generation","Always recursive","Small data only","Different results"],
 answer:0,
 exp_zh:"Han 2000 的 FP-Growth 只需 2 次掃描資料庫即可建樹再挖掘，通常較 Apriori 快數倍。",
 exp_en:"Han (2000) FP-Growth needs only two DB scans to build the tree and mine, often several× faster than Apriori."},
{ch:11,type:'single',
 stem_zh:"關聯規則中的 leverage = support(X∪Y) − support(X)·support(Y) 描述？",
 stem_en:"In association rules, leverage = support(X∪Y) − support(X)·support(Y) describes?",
 options_zh:["實際共同出現超過獨立預期的程度","純隨機程度","支持度誤差","資料缺失"],
 options_en:["How much joint occurrence exceeds independence","Pure randomness","Support error","Missing data"],
 answer:0,
 exp_zh:"leverage 為共現量超過獨立假設的差異，0 即獨立，越正越強。",
 exp_en:"Leverage measures co-occurrence above the independence baseline; 0 means independent, positive means stronger."},
{ch:11,type:'single',
 stem_zh:"ASEA / ARM 在醫療領域常用於？",
 stem_en:"Association rule mining in healthcare commonly serves to?",
 options_zh:["找尋共病模式或藥物副作用同現","電子病歷加密","CT 影像重建","醫師班表排程"],
 options_en:["Find comorbidity patterns or co-occurring drug ADEs","EHR encryption","CT reconstruction","Physician scheduling"],
 answer:0,
 exp_zh:"關聯規則可挖掘共病、共處方、ADE 同現等臨床模式（如 OMOP 上的 ASEA 研究）。",
 exp_en:"Association rules surface comorbidities, co-prescribing, and ADE co-occurrence (e.g., ASEA studies on OMOP)."},
{ch:11,type:'multi',
 stem_zh:"以下哪些是常見的關聯規則度量？(複選)",
 stem_en:"Which are common association-rule measures? (multi-select)",
 options_zh:["support","confidence","lift","gradient"],
 options_en:["support","confidence","lift","gradient"],
 answer:[0,1,2],
 exp_zh:"support/confidence/lift/leverage/conviction 為常見度量；gradient 屬最佳化。",
 exp_en:"support / confidence / lift / leverage / conviction are common; gradient belongs to optimization."},
{ch:11,type:'multi',
 stem_zh:"以下哪些屬於頻繁項集挖掘演算法？(複選)",
 stem_en:"Which are frequent-itemset mining algorithms? (multi-select)",
 options_zh:["Apriori","FP-Growth","ECLAT","PageRank"],
 options_en:["Apriori","FP-Growth","ECLAT","PageRank"],
 answer:[0,1,2],
 exp_zh:"PageRank 是圖排序演算法；前三項為頻繁項集挖掘代表。",
 exp_en:"PageRank ranks graph nodes; the first three are classic frequent-itemset miners."},
{ch:11,type:'tf',
 stem_zh:"提高 minimum support 閾值會減少產出的頻繁項集數量。",
 stem_en:"Raising the minimum support threshold reduces the number of frequent itemsets produced.",
 answer:1,
 exp_zh:"對。support 門檻越高，符合的項集越少；可加速但也錯失稀有但有意義的規則。",
 exp_en:"True. Higher thresholds retain fewer itemsets — faster but may miss rare-yet-meaningful patterns."},
{ch:11,type:'tf',
 stem_zh:"高 confidence 必然代表高 lift。",
 stem_en:"High confidence necessarily implies high lift.",
 answer:0,
 exp_zh:"錯。若 support(Y) 本來就高，confidence 高也可能 lift≈1（無關聯）。",
 exp_en:"False. If support(Y) is already high, confidence can be high while lift≈1 (no association)."},

/* ========== Ch.12 序列樣式探勘 ========== */
{ch:12,type:'single',
 stem_zh:"序列樣式挖掘 (sequential pattern mining) 與一般關聯規則最大差別是？",
 stem_en:"Sequential pattern mining differs from association rules most in?",
 options_zh:["重視項目間時間/順序關係","只能用於文本","不需 minimum support","計算更簡單"],
 options_en:["Considers temporal/order relations between items","Text only","No min support","Simpler compute"],
 answer:0,
 exp_zh:"關聯規則只看共現；序列樣式進一步考慮交易時間順序（A 後出現 B）。",
 exp_en:"Association rules consider co-occurrence; sequential patterns add temporal order (A then B)."},
{ch:12,type:'single',
 stem_zh:"GSP (Generalized Sequential Pattern) 採用何種策略？",
 stem_en:"GSP (Generalized Sequential Pattern) uses what strategy?",
 options_zh:["類 Apriori 的候選生成與剪枝","深度學習","隨機投影","蒙地卡羅"],
 options_en:["Apriori-style candidate generation and pruning","Deep learning","Random projection","Monte Carlo"],
 answer:0,
 exp_zh:"GSP (Srikant & Agrawal 1996) 是序列版 Apriori：產生 k+1 候選 → 計支持度 → 剪枝。",
 exp_en:"GSP (Srikant & Agrawal 1996) is the sequential Apriori: generate k+1 candidates, count support, prune."},
{ch:12,type:'single',
 stem_zh:"SPADE 演算法的關鍵資料結構是？",
 stem_en:"SPADE's key data structure is?",
 options_zh:["垂直 id-list","水平 FP-tree","紅黑樹","Bloom filter"],
 options_en:["Vertical id-list","Horizontal FP-tree","Red-black tree","Bloom filter"],
 answer:0,
 exp_zh:"SPADE (Zaki 2001) 使用 vertical id-list 加上 lattice 結構交集，比 GSP 掃描更快。",
 exp_en:"SPADE (Zaki 2001) uses a vertical id-list with lattice-based intersection, faster than GSP scans."},
{ch:12,type:'single',
 stem_zh:"PrefixSpan 的核心想法是？",
 stem_en:"PrefixSpan's core idea is?",
 options_zh:["以前綴投影 (projection) 將資料庫遞迴縮減","FP-tree","隨機抽樣","強化學習"],
 options_en:["Prefix projection that recursively shrinks the DB","FP-tree","Random sampling","Reinforcement learning"],
 answer:0,
 exp_zh:"PrefixSpan (Pei 2001) 不需候選生成，以前綴投影遞迴挖掘，效能更佳。",
 exp_en:"PrefixSpan (Pei 2001) avoids candidate generation by recursively projecting on prefixes — more efficient."},
{ch:12,type:'single',
 stem_zh:"closed sequential pattern（封閉序列樣式）的定義是？",
 stem_en:"A closed sequential pattern is defined as?",
 options_zh:["沒有任何超序列具有相同支持度","支持度最大","長度最長","在所有交易中出現"],
 options_en:["No supersequence has the same support","Highest support","Longest","Appears in every transaction"],
 answer:0,
 exp_zh:"closed 序列保留全部資訊但壓縮數量（CloSpan 演算法）。",
 exp_en:"A closed sequence retains full information while compressing the output (CloSpan algorithm)."},
{ch:12,type:'single',
 stem_zh:"PM4Py 是何種任務的常用 Python 套件？",
 stem_en:"PM4Py is a common Python library for what?",
 options_zh:["流程探勘 (process mining)","深度學習","關聯規則","網路爬蟲"],
 options_en:["Process mining","Deep learning","Association rules","Web scraping"],
 answer:0,
 exp_zh:"PM4Py 提供從事件日誌挖掘流程模型（Petri net 等）的工具，廣用於醫療流程分析。",
 exp_en:"PM4Py mines process models (Petri nets etc.) from event logs — widely used in clinical-pathway analysis."},
{ch:12,type:'multi',
 stem_zh:"以下哪些屬於序列樣式挖掘演算法？(複選)",
 stem_en:"Which are sequential-pattern mining algorithms? (multi-select)",
 options_zh:["GSP","SPADE","PrefixSpan","K-Means"],
 options_en:["GSP","SPADE","PrefixSpan","K-Means"],
 answer:[0,1,2],
 exp_zh:"K-Means 是分群；前三項為序列挖掘代表。",
 exp_en:"K-Means is clustering; the first three are sequence miners."},
{ch:12,type:'multi',
 stem_zh:"序列樣式挖掘的典型應用情境包含？(複選)",
 stem_en:"Typical applications of sequential pattern mining include? (multi-select)",
 options_zh:["臨床用藥順序","網站點擊流分析","電子病歷事件序列","CT 影像分割"],
 options_en:["Clinical drug sequences","Web clickstream analysis","EHR event sequences","CT image segmentation"],
 answer:[0,1,2],
 exp_zh:"影像分割屬於電腦視覺；前三項為序列挖掘典型應用。",
 exp_en:"Image segmentation is CV; the first three are textbook sequence-mining uses."},
{ch:12,type:'tf',
 stem_zh:"序列樣式 ⟨A, B⟩ 與 ⟨B, A⟩ 視為相同樣式。",
 stem_en:"Sequential patterns ⟨A, B⟩ and ⟨B, A⟩ are considered the same.",
 answer:0,
 exp_zh:"錯。序列在意順序，A 後 B 與 B 後 A 為不同樣式。",
 exp_en:"False. Sequences are order-sensitive — A-then-B ≠ B-then-A."},
{ch:12,type:'tf',
 stem_zh:"PrefixSpan 不需要顯式產生候選序列。",
 stem_en:"PrefixSpan does not need to explicitly generate candidate sequences.",
 answer:1,
 exp_zh:"對。它以前綴投影遞迴挖掘，省去候選生成步驟。",
 exp_en:"True. It uses recursive prefix projection, skipping candidate generation."},

/* ========== Ch.13 異常偵測 ========== */
{ch:13,type:'single',
 stem_zh:"Isolation Forest 判斷異常的原理是？",
 stem_en:"Isolation Forest detects anomalies by?",
 options_zh:["異常點所需切割次數較少（path length 較短）","異常點密度較高","異常點 PCA 解釋率高","異常點群集較大"],
 options_en:["Anomalies require fewer splits (shorter path length)","Anomalies have higher density","Anomalies have higher PCA variance","Anomalies cluster larger"],
 answer:0,
 exp_zh:"Liu 2008 觀察：隨機切分時異常點更快被隔離，平均 path length 較短。",
 exp_en:"Liu (2008): under random splits, anomalies are isolated faster, yielding shorter average path lengths."},
{ch:13,type:'single',
 stem_zh:"LOF (Local Outlier Factor) 的核心想法是？",
 stem_en:"The core idea of LOF (Local Outlier Factor) is?",
 options_zh:["比較某點密度與其鄰居密度的比率","全域距離排序","與中心點距離","僅看絕對密度"],
 options_en:["Compare a point's density to its neighbors' density","Global distance ranking","Distance to centroid","Just absolute density"],
 answer:0,
 exp_zh:"LOF (Breunig 2000) 取點與鄰居局部可達密度的比；> 1 即相對較稀疏，視為異常。",
 exp_en:"LOF (Breunig 2000) uses the ratio of a point's local reachability density to its neighbors'; >1 means relatively sparse → anomaly."},
{ch:13,type:'single',
 stem_zh:"ECOD 異常分數的構造為何？",
 stem_en:"ECOD constructs its anomaly score by?",
 options_zh:["以各維邊際 CDF 的對數加總","用深度神經網路","隨機投影","SVD 分解"],
 options_en:["Summing log of marginal CDFs per dimension","Deep neural network","Random projection","SVD"],
 answer:0,
 exp_zh:"ECOD (Li 2022) 利用經驗 CDF 在尾端的稀有度給分，無參數且具可解釋性。",
 exp_en:"ECOD (Li 2022) scores by tail rarity of empirical marginal CDFs — parameter-free and interpretable."},
{ch:13,type:'single',
 stem_zh:"PyOD 2.x 引入了哪一項新能力？",
 stem_en:"PyOD 2.x introduces which new capability?",
 options_zh:["LLM-based model selection","只支援 GPU","完全去除 sklearn","禁用 ECOD"],
 options_en:["LLM-based model selection","GPU only","Removes sklearn entirely","Disables ECOD"],
 answer:0,
 exp_zh:"PyOD 2.x（2024）整合 LLM 協助根據資料特性自動建議異常偵測模型。",
 exp_en:"PyOD 2.x (2024) integrates LLMs to suggest detectors based on dataset characteristics."},
{ch:13,type:'single',
 stem_zh:"以 Autoencoder 進行異常偵測，常用的『異常分數』是？",
 stem_en:"For Autoencoder-based anomaly detection, the common anomaly score is?",
 options_zh:["重建誤差 (reconstruction error)","梯度範數","網路深度","訓練 epoch 數"],
 options_en:["Reconstruction error","Gradient norm","Network depth","Training epoch count"],
 answer:0,
 exp_zh:"AE 在常態樣本重建良好；異常樣本重建誤差較大。",
 exp_en:"AE reconstructs normal data well; anomalies have larger reconstruction error."},
{ch:13,type:'single',
 stem_zh:"金融詐欺偵測常面臨的核心挑戰是？",
 stem_en:"A core challenge in fraud detection is?",
 options_zh:["極度不平衡與概念漂移","資料完全乾淨","樣本無限多","沒有時序"],
 options_en:["Extreme imbalance and concept drift","Perfectly clean data","Infinite samples","No temporal dimension"],
 answer:0,
 exp_zh:"詐欺率常 < 1%，且詐騙手法隨時間變化（concept drift），需動態模型與適當指標。",
 exp_en:"Fraud rate is often <1% and tactics shift over time (concept drift), requiring adaptive models and appropriate metrics."},
{ch:13,type:'multi',
 stem_zh:"以下哪些是無監督異常偵測方法？(複選)",
 stem_en:"Which are unsupervised anomaly-detection methods? (multi-select)",
 options_zh:["Isolation Forest","LOF","One-Class SVM","Logistic Regression"],
 options_en:["Isolation Forest","LOF","One-Class SVM","Logistic Regression"],
 answer:[0,1,2],
 exp_zh:"Logistic Regression 是監督分類；前三項為無監督異常偵測代表。",
 exp_en:"Logistic Regression is supervised; the first three are unsupervised anomaly detectors."},
{ch:13,type:'multi',
 stem_zh:"處理高度不平衡的異常偵測，下列做法合理的有？(複選)",
 stem_en:"For highly imbalanced anomaly detection, which are sensible? (multi-select)",
 options_zh:["以 PR-AUC 為主要指標","採無監督方法","使用 cost-sensitive 學習","以 accuracy 為唯一指標"],
 options_en:["Use PR-AUC as primary metric","Use unsupervised methods","Use cost-sensitive learning","Use accuracy as the sole metric"],
 answer:[0,1,2],
 exp_zh:"極度不平衡下 accuracy 失去意義（全猜陰性即極高）。",
 exp_en:"Under heavy imbalance, accuracy is meaningless (predict-all-negative scores high)."},
{ch:13,type:'tf',
 stem_zh:"異常偵測通常具有極度不平衡的類別分布。",
 stem_en:"Anomaly detection typically has highly imbalanced class distribution.",
 answer:1,
 exp_zh:"對。異常往往遠少於常態，這是其核心挑戰。",
 exp_en:"True. Anomalies are far rarer than normals — the core challenge."},
{ch:13,type:'tf',
 stem_zh:"Isolation Forest 的 path length 越長代表越異常。",
 stem_en:"In Isolation Forest, longer path length means more anomalous.",
 answer:0,
 exp_zh:"錯。越異常越容易被隔離，path length 越短；分數隨 path length 縮短而升高。",
 exp_en:"False. More anomalous → faster isolation → shorter path. Anomaly score grows as path length shrinks."},

/* ========== Ch.14 文本探勘與 NLP ========== */
{ch:14,type:'single',
 stem_zh:"TF-IDF 中 IDF 的公式為？",
 stem_en:"In TF-IDF, the formula for IDF is?",
 options_zh:["log(N/df)","log(df/N)","N·df","df²"],
 options_en:["log(N/df)","log(df/N)","N·df","df²"],
 answer:0,
 exp_zh:"IDF = log(N/df)（常加 1 平滑）；越罕見的詞 IDF 越大，與常見詞區分。",
 exp_en:"IDF = log(N/df) (often smoothed); rarer terms get higher IDF, distinguishing them from common ones."},
{ch:14,type:'single',
 stem_zh:"停用詞 (stop words) 處理的主要目的是？",
 stem_en:"The main purpose of removing stop words is?",
 options_zh:["移除高頻但低資訊量的詞","加密文字","壓縮字典","保留所有符號"],
 options_en:["Remove high-frequency, low-information words","Encrypt text","Compress vocabulary","Keep all punctuation"],
 answer:0,
 exp_zh:"the/a/and/的/了 等普遍出現，去除可降維與聚焦關鍵詞。",
 exp_en:"Words like the/a/and/的/了 occur everywhere; removing them reduces dimensionality and highlights keywords."},
{ch:14,type:'single',
 stem_zh:"LDA (Latent Dirichlet Allocation) 假設文件由什麼產生？",
 stem_en:"LDA (Latent Dirichlet Allocation) assumes documents are generated from?",
 options_zh:["主題的混合，每個主題是詞分布","單一主題","隨機文字","固定的文法樹"],
 options_en:["A mixture of topics, each topic a word distribution","A single topic","Random words","Fixed grammar tree"],
 answer:0,
 exp_zh:"Blei 2003：每篇文章先抽 Dirichlet 主題分布，再依主題分布抽詞；屬生成模型。",
 exp_en:"Blei 2003: per doc, draw a Dirichlet topic mix; then draw words from topic distributions — a generative model."},
{ch:14,type:'single',
 stem_zh:"Word2Vec 中 Skip-gram 與 CBOW 的差別是？",
 stem_en:"Word2Vec's Skip-gram vs CBOW differ in?",
 options_zh:["Skip-gram 從中心詞預測上下文；CBOW 從上下文預測中心詞","完全相同","只差學習率","只能用 GPU"],
 options_en:["Skip-gram predicts context from center word; CBOW predicts center from context","Identical","Only learning rate","GPU only"],
 answer:0,
 exp_zh:"Mikolov 2013：Skip-gram 對罕見詞較好，CBOW 訓練較快。",
 exp_en:"Mikolov 2013: Skip-gram performs better on rare words; CBOW trains faster."},
{ch:14,type:'single',
 stem_zh:"BioBERT 相較 BERT 主要差別是？",
 stem_en:"BioBERT differs from BERT mainly in?",
 options_zh:["在 PubMed 與 PMC 生醫語料上做領域預訓練","架構完全不同","只支援中文","不能 fine-tune"],
 options_en:["Domain pre-trained on PubMed and PMC biomedical corpora","Different architecture","Chinese only","No fine-tuning"],
 answer:0,
 exp_zh:"Lee 2019 BioBERT 沿用 BERT 架構，於生醫文獻續訓，提升 NER/QA 表現。",
 exp_en:"Lee 2019 BioBERT keeps the BERT architecture but continues pre-training on biomedical text, improving NER/QA."},
{ch:14,type:'single',
 stem_zh:"以下何者最不屬於 NLP 預處理常見步驟？",
 stem_en:"Which is LEAST a typical NLP preprocessing step?",
 options_zh:["分詞 (tokenization)","小寫化","stemming/lemmatization","Conv2D 卷積"],
 options_en:["Tokenization","Lowercasing","Stemming/lemmatization","Conv2D convolution"],
 answer:3,
 exp_zh:"Conv2D 屬於 CV / 模型內運算；前三項是 NLP 文本預處理基本步驟。",
 exp_en:"Conv2D is CV/model internals; the first three are basic NLP preprocessing."},
{ch:14,type:'multi',
 stem_zh:"以下哪些屬於文本表示方法？(複選)",
 stem_en:"Which are text representation methods? (multi-select)",
 options_zh:["TF-IDF","Word2Vec","BERT embeddings","Stochastic gradient descent"],
 options_en:["TF-IDF","Word2Vec","BERT embeddings","Stochastic gradient descent"],
 answer:[0,1,2],
 exp_zh:"SGD 是最佳化演算法；前三項皆為文本向量化方法。",
 exp_en:"SGD is an optimizer; the first three are text vectorizers."},
{ch:14,type:'multi',
 stem_zh:"中文 NLP 常見處理工具包含？(複選)",
 stem_en:"Common Chinese-NLP tools include? (multi-select)",
 options_zh:["jieba","CKIP","HanLP","ImageNet"],
 options_en:["jieba","CKIP","HanLP","ImageNet"],
 answer:[0,1,2],
 exp_zh:"ImageNet 是影像資料集；前三者為主流中文分詞/NLP 工具。",
 exp_en:"ImageNet is a vision dataset; the others are mainstream Chinese NLP tools."},
{ch:14,type:'tf',
 stem_zh:"TF-IDF 比單純 BoW 更能凸顯區別性詞彙。",
 stem_en:"TF-IDF highlights discriminative terms better than plain BoW.",
 answer:1,
 exp_zh:"對。IDF 加權壓低普遍詞、放大罕見詞，使分類/檢索表現通常更好。",
 exp_en:"True. IDF down-weights common terms and amplifies rare ones, often improving classification/retrieval."},
{ch:14,type:'tf',
 stem_zh:"BERT 是基於 Transformer encoder 的雙向語言模型。",
 stem_en:"BERT is a bidirectional language model based on a Transformer encoder.",
 answer:1,
 exp_zh:"對。Devlin 2018 BERT 透過 masked language modeling 學雙向上下文表示。",
 exp_en:"True. Devlin 2018 BERT learns bidirectional context via masked language modeling."},

/* ========== Ch.15 時序資料探勘 ========== */
{ch:15,type:'single',
 stem_zh:"ADF (Augmented Dickey-Fuller) 檢定的虛無假設是？",
 stem_en:"The null hypothesis of the Augmented Dickey-Fuller (ADF) test is?",
 options_zh:["序列存在單位根（非平穩）","序列為白噪聲","存在季節性","序列平穩"],
 options_en:["The series has a unit root (non-stationary)","The series is white noise","Seasonality exists","Series is stationary"],
 answer:0,
 exp_zh:"H0=存在單位根；拒絕 H0 才能視為平穩，是 ARIMA 建模前的常用檢驗。",
 exp_en:"H0 = unit root present; rejecting H0 supports stationarity — common before ARIMA modeling."},
{ch:15,type:'single',
 stem_zh:"ARIMA(p, d, q) 中 d 代表？",
 stem_en:"In ARIMA(p, d, q), d denotes?",
 options_zh:["差分階數","AR 階","MA 階","季節週期"],
 options_en:["Order of differencing","AR order","MA order","Seasonal period"],
 answer:0,
 exp_zh:"d 為使序列變平穩所需的差分次數；p、q 分別為自回歸與移動平均階數。",
 exp_en:"d is the number of differences needed to make the series stationary; p, q are AR and MA orders."},
{ch:15,type:'single',
 stem_zh:"DTW 在時序分類中相較 Euclidean 距離的主要優勢是？",
 stem_en:"For time-series classification, DTW's main advantage over Euclidean is?",
 options_zh:["容許時間軸彈性對齊","必為線性","計算更快","完全等同"],
 options_en:["Allows flexible time-axis alignment","Always linear","Faster","Identical"],
 answer:0,
 exp_zh:"DTW 透過動態規劃找最佳對齊，對相位/速度差較不敏感。",
 exp_en:"DTW finds the optimal alignment via DP, making it robust to phase/speed differences."},
{ch:15,type:'single',
 stem_zh:"Matrix Profile 主要用於發掘？",
 stem_en:"Matrix Profile is mainly used to discover?",
 options_zh:["motif 與 discord","平均值","週期性正弦波","資料缺失"],
 options_en:["Motifs and discords","Means","Periodic sines","Missingness"],
 answer:0,
 exp_zh:"Matrix Profile (Yeh 2016) 透過所有子序列最近鄰距離快速找出 motif (重複) 與 discord (異常)。",
 exp_en:"Matrix Profile (Yeh 2016) uses every subsequence's nearest-neighbor distance to find motifs (repetitions) and discords (anomalies)."},
{ch:15,type:'single',
 stem_zh:"在時間序列中找突變點 (change point) 的常見指標是？",
 stem_en:"For change-point detection in time series, a common criterion is?",
 options_zh:["分布變化的對數似然比 / PELT cost","平均值","隨機指標","ROC"],
 options_en:["Log-likelihood ratio of distribution change / PELT cost","Mean","Random","ROC"],
 answer:0,
 exp_zh:"CUSUM、Bayesian online、PELT 等以分布/似然變化偵測 change point。",
 exp_en:"CUSUM, Bayesian online, PELT etc. detect change points via distribution/likelihood shifts."},
{ch:15,type:'single',
 stem_zh:"季節分解 (STL) 的三個成分為？",
 stem_en:"STL decomposition outputs which three components?",
 options_zh:["趨勢 / 季節 / 殘差","平均 / 變異 / 偏度","AR / MA / ARMA","週 / 月 / 年"],
 options_en:["Trend / Seasonal / Residual","Mean / Var / Skew","AR / MA / ARMA","Week / Month / Year"],
 answer:0,
 exp_zh:"STL (Cleveland 1990) 將時序拆為 trend、seasonal、residual。",
 exp_en:"STL (Cleveland 1990) decomposes a series into trend, seasonal and residual."},
{ch:15,type:'multi',
 stem_zh:"以下哪些是時序預測模型？(複選)",
 stem_en:"Which are time-series forecasting models? (multi-select)",
 options_zh:["ARIMA","Prophet","LSTM","DBSCAN"],
 options_en:["ARIMA","Prophet","LSTM","DBSCAN"],
 answer:[0,1,2],
 exp_zh:"DBSCAN 是分群；前三項為時序預測常見模型。",
 exp_en:"DBSCAN is clustering; the first three are common forecasting models."},
{ch:15,type:'multi',
 stem_zh:"以下哪些是時序資料中需特別注意的問題？(複選)",
 stem_en:"Which issues need special attention with time-series data? (multi-select)",
 options_zh:["不可隨機切分（要用時間順序）","平穩性檢定","季節性處理","可忽略時間順序"],
 options_en:["No random split (use time order)","Stationarity testing","Seasonality handling","Time order can be ignored"],
 answer:[0,1,2],
 exp_zh:"忽略時間順序會造成 future-leakage；前三項是時序基本準則。",
 exp_en:"Ignoring time order causes future leakage; the first three are basic time-series rules."},
{ch:15,type:'tf',
 stem_zh:"在時序預測上隨機 K-fold 是公平的評估方式。",
 stem_en:"Random K-fold is a fair evaluation for time-series forecasting.",
 answer:0,
 exp_zh:"錯。會用未來預測過去（leakage）；應使用 time-series split / walk-forward。",
 exp_en:"False. It uses the future to predict the past (leakage); use time-series split / walk-forward."},
{ch:15,type:'tf',
 stem_zh:"白噪聲序列在 ACF 上各 lag 的相關幾乎為 0。",
 stem_en:"For white noise, ACF at each lag is approximately 0.",
 answer:1,
 exp_zh:"對。白噪聲互不相關，理論 ACF 在非零 lag 期望為 0。",
 exp_en:"True. White noise is uncorrelated, so non-zero-lag ACF is 0 in expectation."},

/* ========== Ch.16 圖與網絡探勘 ========== */
{ch:16,type:'single',
 stem_zh:"PageRank 演算法的核心模型是？",
 stem_en:"PageRank's core model is?",
 options_zh:["隨機漫步加阻尼 (damping)","梯度下降","K-Means","ARIMA"],
 options_en:["Random walk with damping","Gradient descent","K-Means","ARIMA"],
 answer:0,
 exp_zh:"PageRank (Brin & Page 1998) 以隨機漫步在網頁圖上 + 阻尼項 d≈0.85，迭代直到穩態分布。",
 exp_en:"PageRank (Brin & Page 1998) iterates a random walk with damping d≈0.85 on the web graph until stationary."},
{ch:16,type:'single',
 stem_zh:"Louvain 演算法以最大化哪一個指標進行社群偵測？",
 stem_en:"Louvain detects communities by maximizing which metric?",
 options_zh:["Modularity Q","Gini","Silhouette","Entropy"],
 options_en:["Modularity Q","Gini","Silhouette","Entropy"],
 answer:0,
 exp_zh:"Blondel 2008 Louvain 以貪婪局部移動最大化 modularity。",
 exp_en:"Blondel 2008 Louvain greedily moves nodes to maximize modularity."},
{ch:16,type:'single',
 stem_zh:"Leiden 演算法相對 Louvain 的主要改進是？",
 stem_en:"Leiden's main improvement over Louvain is?",
 options_zh:["保證每個社群內連通且更穩定","完全等同","只支援無向","禁用 modularity"],
 options_en:["Guarantees each community is connected and is more stable","Identical","Undirected only","Removes modularity"],
 answer:0,
 exp_zh:"Traag 2019 Leiden 修正 Louvain 可能產出非連通社群的缺陷，並加入細化步驟。",
 exp_en:"Traag 2019 Leiden fixes Louvain's tendency to produce disconnected communities and adds a refinement step."},
{ch:16,type:'single',
 stem_zh:"node2vec 透過哪兩個參數控制隨機漫步偏好？",
 stem_en:"node2vec's biased random walk is controlled by which two parameters?",
 options_zh:["p (return) 與 q (in-out)","α 與 β","λ 與 μ","k 與 ε"],
 options_en:["p (return) and q (in-out)","α and β","λ and μ","k and ε"],
 answer:0,
 exp_zh:"Grover & Leskovec 2016：p 控制回到上一節點傾向，q 控制離開鄰域傾向，可在 DFS/BFS 風格間切換。",
 exp_en:"Grover & Leskovec 2016: p controls returning to the previous node; q controls leaving the local neighborhood — interpolating BFS/DFS."},
{ch:16,type:'single',
 stem_zh:"GNN (Graph Neural Network) 的核心運算是？",
 stem_en:"The core operation of a Graph Neural Network (GNN) is?",
 options_zh:["訊息傳遞 (message passing) 與鄰居聚合","CNN 卷積","RNN 遞迴","Attention 全連接"],
 options_en:["Message passing & neighbor aggregation","CNN convolution","RNN recurrence","Fully attention"],
 answer:0,
 exp_zh:"GNN 在每層收集鄰居訊息並聚合更新節點向量（GCN/GraphSAGE/GAT 等）。",
 exp_en:"Each GNN layer collects messages from neighbors and aggregates to update node embeddings (GCN/GraphSAGE/GAT)."},
{ch:16,type:'single',
 stem_zh:"以下何者最常用來衡量節點在網絡中的『橋接』重要性？",
 stem_en:"Which best measures a node's 'bridging' importance in a network?",
 options_zh:["betweenness centrality","degree","closeness","clustering coefficient"],
 options_en:["betweenness centrality","degree","closeness","clustering coefficient"],
 answer:0,
 exp_zh:"betweenness 計算節點位於最短路徑上的比例，反映橋接 / 仲介角色。",
 exp_en:"Betweenness counts a node's share on shortest paths — reflecting its bridge/broker role."},
{ch:16,type:'multi',
 stem_zh:"以下哪些是社群偵測 (community detection) 演算法？(複選)",
 stem_en:"Which are community-detection algorithms? (multi-select)",
 options_zh:["Louvain","Leiden","Label Propagation","K-Means"],
 options_en:["Louvain","Leiden","Label Propagation","K-Means"],
 answer:[0,1,2],
 exp_zh:"K-Means 是一般分群；前三項為社群偵測代表。",
 exp_en:"K-Means is general clustering; the others are community-detection algorithms."},
{ch:16,type:'multi',
 stem_zh:"圖嵌入 (graph embedding) 的常見方法包含？(複選)",
 stem_en:"Common graph-embedding methods include? (multi-select)",
 options_zh:["DeepWalk","node2vec","GraphSAGE","Apriori"],
 options_en:["DeepWalk","node2vec","GraphSAGE","Apriori"],
 answer:[0,1,2],
 exp_zh:"Apriori 是關聯規則；前三項為圖嵌入代表。",
 exp_en:"Apriori is association rules; the others are graph embeddings."},
{ch:16,type:'tf',
 stem_zh:"PageRank 的阻尼係數通常設為 0.85。",
 stem_en:"PageRank's damping factor is typically set to 0.85.",
 answer:1,
 exp_zh:"對。Brin & Page 原論文即建議 d≈0.85，平衡隨機跳轉與鏈結傳遞。",
 exp_en:"True. Brin & Page recommend d≈0.85, balancing teleport and link-follow."},
{ch:16,type:'tf',
 stem_zh:"小世界網絡 (small-world) 同時具有高聚類係數與短平均路徑。",
 stem_en:"A small-world network has both high clustering and short average path length.",
 answer:1,
 exp_zh:"對。Watts & Strogatz 1998 定義了 small-world 的兩個關鍵特徵。",
 exp_en:"True. Watts & Strogatz 1998 defined small-world by these two properties."},

/* ========== Ch.17 EHR 資料探勘 ========== */
{ch:17,type:'single',
 stem_zh:"ICD-9 與 ICD-10 最大差別是？",
 stem_en:"The largest difference between ICD-9 and ICD-10 is?",
 options_zh:["ICD-10 編碼數量遠多於 ICD-9 且結構不同","完全等同","ICD-10 只用於精神疾病","ICD-9 為英文版"],
 options_en:["ICD-10 has far more codes than ICD-9 with different structure","Identical","ICD-10 is psychiatric only","ICD-9 is English-only"],
 answer:0,
 exp_zh:"ICD-10 ≈ 14000 vs ICD-9 ≈ 13000 + 結構不同 + 美國 2015 才換 ICD-10-CM。",
 exp_en:"ICD-10 has ~14k codes vs ICD-9's ~13k with different structure; US switched to ICD-10-CM only in 2015."},
{ch:17,type:'single',
 stem_zh:"SNOMED CT 是一種？",
 stem_en:"SNOMED CT is?",
 options_zh:["臨床術語的本體 (ontology)，比 ICD 更細緻","影像格式","疾病基因資料庫","醫材編碼"],
 options_en:["A clinical-terminology ontology, finer-grained than ICD","Image format","Disease-gene DB","Device coding"],
 answer:0,
 exp_zh:"SNOMED CT 為國際標準臨床術語，包含病症、解剖、處置等概念與關係。",
 exp_en:"SNOMED CT is an international clinical-terminology ontology covering conditions, anatomy, procedures and relations."},
{ch:17,type:'single',
 stem_zh:"OMOP CDM 主要目的為？",
 stem_en:"OMOP CDM's main goal is?",
 options_zh:["跨機構統一電子病歷資料模型以利協作研究","加密病歷","產生帳單","儲存影像"],
 options_en:["Standardize EHR data model across sites for collaborative research","Encrypt charts","Generate bills","Store images"],
 answer:0,
 exp_zh:"OHDSI 推動的 OMOP CDM 將多源 EHR 映射到共同 schema，支援大規模觀察研究。",
 exp_en:"OHDSI's OMOP CDM maps multi-source EHRs onto a shared schema, enabling large-scale observational research."},
{ch:17,type:'single',
 stem_zh:"PheKB 主要用於？",
 stem_en:"PheKB is mainly used for?",
 options_zh:["分享經過驗證的電子病歷 phenotype 演算法","醫材交易","臨床試驗註冊","資料加密"],
 options_en:["Sharing validated electronic phenotyping algorithms from EHR","Medical-device trade","Trial registry","Data encryption"],
 answer:0,
 exp_zh:"PheKB (Phenotype KnowledgeBase) 是公開的電子表型 (e-phenotyping) 演算法庫。",
 exp_en:"PheKB is a public repository of validated electronic phenotyping algorithms."},
{ch:17,type:'single',
 stem_zh:"Kaplan-Meier 曲線適用於？",
 stem_en:"Kaplan-Meier curves are used for?",
 options_zh:["生存分析中的非參數估計","回歸殘差檢定","關聯規則 lift","CT 影像重建"],
 options_en:["Non-parametric estimation in survival analysis","Regression residual check","Association lift","CT reconstruction"],
 answer:0,
 exp_zh:"Kaplan-Meier 1958 為生存函數的非參數估計，常用於癌症生存率比較。",
 exp_en:"Kaplan-Meier (1958) is a non-parametric survival-function estimator, common in oncology survival comparisons."},
{ch:17,type:'single',
 stem_zh:"Cox 比例風險模型核心假設是？",
 stem_en:"The core assumption of the Cox proportional-hazards model is?",
 options_zh:["不同組別風險比隨時間保持常數","風險恆為線性","只能用於兩組","樣本必為常態"],
 options_en:["Hazard ratio between groups is constant over time","Hazard is linear","Two groups only","Samples must be normal"],
 answer:0,
 exp_zh:"Cox 1972：h(t|x)=h0(t)exp(βᵀx)；分組風險比與 t 無關（PH 假設），可用 Schoenfeld residuals 檢驗。",
 exp_en:"Cox (1972): h(t|x)=h0(t)exp(βᵀx); hazard ratio across groups is independent of t (PH assumption), testable via Schoenfeld residuals."},
{ch:17,type:'multi',
 stem_zh:"以下哪些是 EHR 探勘常見挑戰？(複選)",
 stem_en:"Which are common challenges in EHR mining? (multi-select)",
 options_zh:["編碼不一致","稀疏與缺失","隱私法規 (HIPAA/GDPR)","資料絕對乾淨"],
 options_en:["Inconsistent coding","Sparsity & missingness","Privacy regulations (HIPAA/GDPR)","Always perfectly clean data"],
 answer:[0,1,2],
 exp_zh:"前三項為 EHR 真實困境；EHR 通常雜訊大、欄位變化多。",
 exp_en:"The first three are real EHR challenges; EHR is typically noisy and heterogeneous."},
{ch:17,type:'multi',
 stem_zh:"在生存分析中處理競爭風險 (competing risk) 的方法包含？(複選)",
 stem_en:"Methods for competing risks in survival analysis include? (multi-select)",
 options_zh:["Fine-Gray subdistribution","cause-specific hazard","cumulative incidence function","Naive Bayes"],
 options_en:["Fine-Gray subdistribution","Cause-specific hazard","Cumulative incidence function","Naive Bayes"],
 answer:[0,1,2],
 exp_zh:"Naive Bayes 為分類器；前三項為競爭風險標準方法。",
 exp_en:"Naive Bayes is a classifier; the first three are standard competing-risk methods."},
{ch:17,type:'tf',
 stem_zh:"EHR 中以 ICD-9-CM 抓取糖尿病病例必然準確抓到所有糖尿病人。",
 stem_en:"Using ICD-9-CM to identify diabetes in EHR captures every true diabetic patient.",
 answer:0,
 exp_zh:"錯。電子表型需考慮 ICD 編碼不完整、編碼錯誤、加上 lab/藥物等多源證據。",
 exp_en:"False. Electronic phenotyping must account for missing/incorrect ICD codes and combine multiple sources (labs, meds)."},
{ch:17,type:'tf',
 stem_zh:"OMOP CDM 對概念 (concept) 採用標準字彙 (standard vocabulary) 對映。",
 stem_en:"OMOP CDM maps concepts via a standard vocabulary.",
 answer:1,
 exp_zh:"對。OMOP 以 standardized vocabularies（SNOMED、RxNorm、LOINC 等）把多源代碼整合。",
 exp_en:"True. OMOP integrates multi-source codes through standardized vocabularies (SNOMED, RxNorm, LOINC, etc.)."},

/* ========== Ch.18 組學資料探勘 ========== */
{ch:18,type:'single',
 stem_zh:"組學資料 (omics) 常見的『p >> n』困境是指？",
 stem_en:"The 'p >> n' challenge in omics refers to?",
 options_zh:["特徵維度遠大於樣本數，易過擬合","樣本數大於特徵","樣本完全相同","資料缺失"],
 options_en:["Feature dimensionality far exceeds sample size, overfitting","More samples than features","All samples identical","Missing data"],
 answer:0,
 exp_zh:"例如 RNA-seq 約兩萬基因 vs 幾百樣本；需正則化、特徵選擇或降維。",
 exp_en:"E.g., RNA-seq has ~20k genes vs hundreds of samples; needs regularization, feature selection or dimensionality reduction."},
{ch:18,type:'single',
 stem_zh:"LASSO (L1 正則化) 在組學資料的主要用途是？",
 stem_en:"LASSO (L1) is mainly used in omics for?",
 options_zh:["特徵選擇與稀疏模型","強化非線性","隨機抽樣","資料增強"],
 options_en:["Feature selection and sparse modeling","Adding nonlinearity","Random sampling","Data augmentation"],
 answer:0,
 exp_zh:"Tibshirani 1996 LASSO 透過 L1 將不重要係數壓到 0，產生稀疏模型適合高維低樣本。",
 exp_en:"Tibshirani 1996 LASSO drives unimportant coefficients to 0 via L1, producing sparse models suitable for high-D/low-n."},
{ch:18,type:'single',
 stem_zh:"Boruta 特徵選擇法的核心想法是？",
 stem_en:"Boruta feature selection's core idea is?",
 options_zh:["把原特徵與 shadow（打亂版）一起餵 RF，比較重要性","只用 LASSO","用 t 檢定","隨機選擇"],
 options_en:["Feed original + shadow (permuted) features into RF; compare importances","Only LASSO","Use t-test","Random select"],
 answer:0,
 exp_zh:"Boruta (Kursa & Rudnicki 2010) 用打亂版作為虛擬基線，比基線重要的特徵才保留。",
 exp_en:"Boruta (Kursa & Rudnicki 2010) uses permuted features as a null baseline; only features beating the baseline are kept."},
{ch:18,type:'single',
 stem_zh:"MOFA+ 用於？",
 stem_en:"MOFA+ is used for?",
 options_zh:["多組學資料的因子分解整合","單細胞影像分割","深度學習加速","蛋白結構預測"],
 options_en:["Factor-analysis-based multi-omics integration","scRNA imaging","DL acceleration","Protein structure"],
 answer:0,
 exp_zh:"MOFA+ (Argelaguet 2020) 將多組學矩陣聯合分解為共享潛在因子，揭示跨資料源訊號。",
 exp_en:"MOFA+ (Argelaguet 2020) jointly factorizes multi-omics matrices into shared latent factors, revealing cross-modal signal."},
{ch:18,type:'single',
 stem_zh:"ComBat 主要用於？",
 stem_en:"ComBat is mainly used for?",
 options_zh:["批次效應 (batch effect) 校正","資料增強","聚類","蛋白序列比對"],
 options_en:["Batch-effect correction","Data augmentation","Clustering","Protein sequence alignment"],
 answer:0,
 exp_zh:"Johnson 2007 ComBat 以經驗貝氏移除批次效應，廣用於微陣列/RNA-seq。",
 exp_en:"Johnson 2007 ComBat removes batch effects via empirical Bayes — widely used for microarray / RNA-seq."},
{ch:18,type:'single',
 stem_zh:"Harmony 演算法用於？",
 stem_en:"Harmony is used for?",
 options_zh:["單細胞資料的批次整合","關聯規則挖掘","異常偵測","ARIMA 預測"],
 options_en:["Single-cell batch integration","Association rules","Anomaly detection","ARIMA forecasting"],
 answer:0,
 exp_zh:"Harmony (Korsunsky 2019) 在 PCA 空間迭代群聚與線性校正，整合不同批次的單細胞資料。",
 exp_en:"Harmony (Korsunsky 2019) iterates clustering and linear correction in PCA space to integrate single-cell batches."},
{ch:18,type:'multi',
 stem_zh:"以下哪些屬於高維組學的常見降維/視覺化方法？(複選)",
 stem_en:"Which are common dimensionality-reduction / visualization methods for omics? (multi-select)",
 options_zh:["PCA","t-SNE","UMAP","K-Means"],
 options_en:["PCA","t-SNE","UMAP","K-Means"],
 answer:[0,1,2],
 exp_zh:"K-Means 是分群；前三項為降維/視覺化代表。",
 exp_en:"K-Means is clustering; the first three are dim-reduction/visualization staples."},
{ch:18,type:'multi',
 stem_zh:"以下哪些是組學資料分析常見議題？(複選)",
 stem_en:"Which are common issues in omics analysis? (multi-select)",
 options_zh:["批次效應","多重檢定校正","資料極度高維","完全沒有缺失"],
 options_en:["Batch effects","Multiple-testing correction","Extremely high dimensions","Never any missingness"],
 answer:[0,1,2],
 exp_zh:"組學經常含缺失與技術噪聲；前三項才是真實議題。",
 exp_en:"Omics commonly has missingness and technical noise; the first three are real issues."},
{ch:18,type:'tf',
 stem_zh:"在高維組學上 raw p < 0.05 即可直接宣告統計顯著。",
 stem_en:"In high-D omics, raw p < 0.05 alone is sufficient to claim statistical significance.",
 answer:0,
 exp_zh:"錯。需做多重檢定校正（FDR、Bonferroni 等），否則偽陽性大量產生。",
 exp_en:"False. Multiple-testing correction (FDR, Bonferroni) is needed to avoid massive false positives."},
{ch:18,type:'tf',
 stem_zh:"PCA 在組學資料中常用來偵測潛在批次效應或離群樣本。",
 stem_en:"In omics, PCA is commonly used to detect latent batch effects or outlier samples.",
 answer:1,
 exp_zh:"對。PCA 圖上若樣本依批次分群，即提示批次效應或實驗設計問題。",
 exp_en:"True. If samples cluster by batch on the PCA plot, batch effects or design issues are likely."},

/* ========== Ch.19 文獻探勘 (PubMed) ========== */
{ch:19,type:'single',
 stem_zh:"MeSH (Medical Subject Headings) 是？",
 stem_en:"MeSH (Medical Subject Headings) is?",
 options_zh:["NLM 維護的受控字彙，用於文獻索引","商業字典","醫材清單","ICD 替代品"],
 options_en:["NLM-curated controlled vocabulary for indexing literature","Commercial dictionary","Device list","ICD replacement"],
 answer:0,
 exp_zh:"NLM 以 MeSH 對 PubMed 文獻做主題索引，是領域文獻檢索的關鍵字彙。",
 exp_en:"NLM uses MeSH to index PubMed articles by topic — a key vocabulary for biomedical literature retrieval."},
{ch:19,type:'single',
 stem_zh:"PubMed E-utilities 中 efetch 主要用途是？",
 stem_en:"In PubMed E-utilities, efetch is mainly used to?",
 options_zh:["以 PMID 取得文獻的詳細記錄 (XML/MEDLINE)","關鍵字搜尋","產生圖表","計算 lift"],
 options_en:["Fetch detailed records (XML/MEDLINE) by PMID","Keyword search","Generate charts","Compute lift"],
 answer:0,
 exp_zh:"E-utilities：esearch（搜尋取 ID）→ efetch（取記錄）→ elink（連結資料庫）。",
 exp_en:"E-utilities: esearch (find IDs) → efetch (retrieve records) → elink (cross-database links)."},
{ch:19,type:'single',
 stem_zh:"BERN2 主要用途為？",
 stem_en:"BERN2 is mainly used for?",
 options_zh:["生醫文獻命名實體辨識 (NER)","關聯規則","CT 重建","回歸預測"],
 options_en:["Biomedical named-entity recognition (NER)","Association rules","CT reconstruction","Regression"],
 answer:0,
 exp_zh:"BERN2 (Kim 2022) 是改良版生醫 NER 系統，能辨識基因、藥物、疾病、突變等實體。",
 exp_en:"BERN2 (Kim 2022) is an upgraded biomedical NER system tagging genes, drugs, diseases, mutations etc."},
{ch:19,type:'single',
 stem_zh:"BioRED 標註集合主要支援哪一任務？",
 stem_en:"The BioRED corpus mainly supports which task?",
 options_zh:["生醫關係抽取 (relation extraction)","CT 影像分類","語音辨識","DNA 比對"],
 options_en:["Biomedical relation extraction","CT classification","Speech recognition","DNA alignment"],
 answer:0,
 exp_zh:"BioRED (Luo 2022) 為跨實體類型的多元生醫關係抽取資料集。",
 exp_en:"BioRED (Luo 2022) is a multi-entity biomedical relation-extraction corpus."},
{ch:19,type:'single',
 stem_zh:"Hetionet 是？",
 stem_en:"Hetionet is?",
 options_zh:["整合多來源的生醫異質圖譜","醫療影像庫","臨床試驗網","基因晶片資料"],
 options_en:["A heterogeneous biomedical knowledge graph integrating multiple sources","Medical image bank","Trial network","Microarray data"],
 answer:0,
 exp_zh:"Hetionet (Himmelstein 2017) 整合 29 種來源、含基因/藥物/疾病等 11 類節點，用於藥物再利用。",
 exp_en:"Hetionet (Himmelstein 2017) integrates 29 sources with 11 node types (genes/drugs/diseases…) for drug repurposing."},
{ch:19,type:'single',
 stem_zh:"以下何者最不屬於文獻探勘的典型輸出？",
 stem_en:"Which is LEAST a typical literature-mining output?",
 options_zh:["藥物-疾病關係圖","共現網絡","研究熱點時序","CT 影像分割掩膜"],
 options_en:["Drug-disease relation graph","Co-occurrence network","Research hotspot timeline","CT segmentation mask"],
 answer:3,
 exp_zh:"CT 分割屬於影像 AI；前三項為文獻探勘常見產出。",
 exp_en:"CT segmentation is medical imaging; the others are typical literature-mining outputs."},
{ch:19,type:'multi',
 stem_zh:"以下哪些是 PubMed/文獻探勘的常見挑戰？(複選)",
 stem_en:"Which are common challenges in PubMed/literature mining? (multi-select)",
 options_zh:["生醫術語的同義詞與縮寫","抓取速率限制 (API rate limit)","句法歧義","資料絕對結構化"],
 options_en:["Biomedical synonyms & abbreviations","API rate limits","Syntactic ambiguity","Fully structured data"],
 answer:[0,1,2],
 exp_zh:"PubMed 摘要為自由文本而非結構化，前三項才是真實挑戰。",
 exp_en:"PubMed abstracts are free text, not structured; the first three are the real challenges."},
{ch:19,type:'multi',
 stem_zh:"藥物再利用 (drug repurposing) 文獻探勘的常見策略包含？(複選)",
 stem_en:"Common strategies in literature-driven drug repurposing include? (multi-select)",
 options_zh:["藥物-基因-疾病三聯路徑","知識圖譜嵌入","文獻共現網絡","CT 影像處理"],
 options_en:["Drug-gene-disease triple paths","Knowledge-graph embedding","Literature co-occurrence networks","CT image processing"],
 answer:[0,1,2],
 exp_zh:"CT 影像處理與文獻探勘無直接關係；前三項為主流方法。",
 exp_en:"CT imaging is unrelated; the first three are mainstream literature-mining strategies."},
{ch:19,type:'tf',
 stem_zh:"PubMed E-utilities 的使用建議遵守 NCBI 的請求頻率限制。",
 stem_en:"Users should respect NCBI's rate limits when using PubMed E-utilities.",
 answer:1,
 exp_zh:"對。一般無 API key 為 3 req/sec，有 API key 為 10 req/sec；超限可能被暫禁。",
 exp_en:"True. Default 3 req/sec without API key, 10 req/sec with one; exceeding may be throttled."},
{ch:19,type:'tf',
 stem_zh:"生醫文獻中縮寫如 'CA' 在不同情境下可能對應不同實體（鈣、癌症等），需做 word sense disambiguation。",
 stem_en:"Biomedical abbreviations like 'CA' may map to different entities (calcium, cancer) in different contexts, requiring WSD.",
 answer:1,
 exp_zh:"對。生醫術語高度多義，WSD/縮寫消歧是 BERN2 等工具的重要任務。",
 exp_en:"True. Biomedical terms are highly polysemous; WSD / abbreviation disambiguation is essential (BERN2 etc.)."},

/* ========== Ch.20 倫理與可重現性 ========== */
{ch:20,type:'single',
 stem_zh:"HIPAA Safe Harbor 規定的去識別化共需移除多少個識別碼？",
 stem_en:"HIPAA Safe Harbor de-identification requires removing how many identifiers?",
 options_zh:["10","14","18","24"],
 options_en:["10","14","18","24"],
 answer:2,
 exp_zh:"45 CFR 164.514(b)(2) 列出 18 個必須移除的識別碼（姓名、地址、日期、電話、Email…）。",
 exp_en:"45 CFR 164.514(b)(2) lists 18 identifiers that must be removed (names, addresses, dates, phones, emails …)."},
{ch:20,type:'single',
 stem_zh:"Latanya Sweeney (2000) 的著名實驗發現美國人口約有多少 % 可由 ZIP + 性別 + 出生日唯一辨識？",
 stem_en:"Latanya Sweeney (2000) found roughly what fraction of the US population is uniquely identified by ZIP + sex + DOB?",
 options_zh:["13%","47%","87%","99%"],
 options_en:["13%","47%","87%","99%"],
 answer:2,
 exp_zh:"~87% 美國人可由 5 位 ZIP + 性別 + 出生日唯一辨識，被視為去識別化基準的關鍵警示。",
 exp_en:"~87% of Americans are uniquely identifiable by 5-digit ZIP + sex + DOB — a landmark warning for de-identification."},
{ch:20,type:'single',
 stem_zh:"demographic parity 與 equalized odds 兩個公平性定義的差別是？",
 stem_en:"Demographic parity vs equalized odds differ in?",
 options_zh:["DP 要求各組陽性預測率相同；EO 進一步要求 TPR/FPR 各組相同","完全相同","DP 只用於回歸","EO 不用標籤"],
 options_en:["DP requires equal positive prediction rates across groups; EO further requires equal TPR/FPR","Identical","DP for regression only","EO ignores labels"],
 answer:0,
 exp_zh:"DP 只看預測比例；EO 條件於真實標籤要求錯誤率均等，後者通常更難達成。",
 exp_en:"DP looks at prediction rates only; EO conditions on true labels to equalize error rates — typically stricter."},
{ch:20,type:'single',
 stem_zh:"EU AI Act 2026 對高風險 AI 系統最關鍵的要求之一是？",
 stem_en:"One key requirement of the EU AI Act 2026 for high-risk AI systems is?",
 options_zh:["風險管理、技術文件與可追溯性","完全禁止使用","只能用開源軟體","僅限歐盟公民"],
 options_en:["Risk management, technical documentation & traceability","Total ban","Open-source only","EU citizens only"],
 answer:0,
 exp_zh:"高風險 AI 須建立風險管理系統、保存技術文件、紀錄與監控、保證透明與人為監督。",
 exp_en:"High-risk AI must implement risk management, keep technical documentation, logging/monitoring, transparency and human oversight."},
{ch:20,type:'single',
 stem_zh:"FAIR 資料原則中的 R 代表？",
 stem_en:"In the FAIR data principles, R stands for?",
 options_zh:["Reusable","Random","Real-time","Restricted"],
 options_en:["Reusable","Random","Real-time","Restricted"],
 answer:0,
 exp_zh:"FAIR = Findable / Accessible / Interoperable / Reusable (Wilkinson 2016)。",
 exp_en:"FAIR = Findable / Accessible / Interoperable / Reusable (Wilkinson 2016)."},
{ch:20,type:'single',
 stem_zh:"以下何者最能提升資料探勘專案的可重現性？",
 stem_en:"Which best improves reproducibility of a data-mining project?",
 options_zh:["固定隨機種子 + 版本控制 + 容器化環境","只儲存最終模型權重","僅口頭交接","以截圖代替程式碼"],
 options_en:["Fixed random seeds + version control + containerized environment","Save only final model weights","Verbal handover only","Screenshots instead of code"],
 answer:0,
 exp_zh:"可重現性需鎖定隨機性、程式碼版本、依賴環境（Docker/conda）與資料版本。",
 exp_en:"Reproducibility needs fixed randomness, code versioning, dependency env (Docker/conda) and data versioning."},
{ch:20,type:'multi',
 stem_zh:"以下哪些屬於 AI 公平性議題？(複選)",
 stem_en:"Which belong to AI fairness concerns? (multi-select)",
 options_zh:["不同族群錯誤率差異","訓練資料偏差","部署後不同人口表現差","訓練時 GPU 利用率"],
 options_en:["Per-subgroup error disparity","Training-data bias","Post-deployment performance gaps","Training GPU utilization"],
 answer:[0,1,2],
 exp_zh:"GPU 利用率屬於效能監控，不是公平性；前三項皆為公平性核心議題。",
 exp_en:"GPU utilization is performance ops, not fairness; the first three are core fairness issues."},
{ch:20,type:'multi',
 stem_zh:"以下哪些做法有助於資料隱私保護？(複選)",
 stem_en:"Which practices help protect data privacy? (multi-select)",
 options_zh:["k-匿名化","差分隱私","聯邦學習","完全公開原始病歷"],
 options_en:["k-anonymity","Differential privacy","Federated learning","Public release of raw EHR"],
 answer:[0,1,2],
 exp_zh:"公開原始病歷會洩漏 PHI；前三項為隱私保護技術。",
 exp_en:"Releasing raw EHR leaks PHI; the first three are privacy-preserving techniques."},
{ch:20,type:'tf',
 stem_zh:"模型卡 (Model Card) 與資料表 (Datasheet for Datasets) 都是促進透明度的工具。",
 stem_en:"Model Cards and Datasheets for Datasets are both transparency tools.",
 answer:1,
 exp_zh:"對。Mitchell 2019 Model Cards 與 Gebru 2018 Datasheets 分別記錄模型與資料的關鍵屬性。",
 exp_en:"True. Mitchell 2019 Model Cards and Gebru 2018 Datasheets document model and dataset characteristics."},
{ch:20,type:'tf',
 stem_zh:"在嚴格的差分隱私 (DP) 機制下，noise 加得越多 ε 通常越小（隱私保護越強）。",
 stem_en:"Under strict differential privacy (DP), more noise generally yields smaller ε (stronger privacy).",
 answer:1,
 exp_zh:"對。ε (privacy budget) 越小代表更強保證；對應加更多噪聲，但效用下降。",
 exp_en:"True. Smaller ε (privacy budget) means stronger guarantees, requiring more noise but reducing utility."}
];
